/**
 * yarn-classic-deep — yarn.lock v1 with pathological shapes.
 *
 * Real yarn v1 lockfiles have a few hundred to a few thousand top-level entries and a
 * handful of comma-joined aliases per key. This generator emits three shapes:
 *
 *   wide-specs      — N distinct top-level package entries. Stresses the O(N) parse
 *                     + graph-build passes in @yarnpkg/lockfile and lockfile-yarn.ts.
 *   long-spec-list  — a single entry with N comma-separated alias specs on one line
 *                     (`foo@^1.0.0, foo@^1.1.0, foo@^1.2.0, ...`). Stresses parser
 *                     tokenization + the `rawKey.split(',')` + parseYarnAlias loop.
 *   alias-chain     — N packages where each depends on the next. Stresses the
 *                     dependency-edge second pass and any downstream graph walker.
 *
 * All outputs pass through @yarnpkg/lockfile's classic parser (no `__metadata:` header).
 * The classic parser is invoked via lockfile-any.ts's detectKind() → yarn-classic route.
 *
 * Deterministic. Same (seed, params) → identical bytes.
 */

import type { RobustnessGenerator, LockfileInput } from './types.js';

export interface YarnClassicDeepParams {
  /** Which pathological shape to emit. */
  readonly mode: 'wide-specs' | 'long-spec-list' | 'alias-chain';
  /** Shape-specific magnitude. Baseline 10 (safe), stress 100/1000+ pins current behavior. */
  readonly scale: number;
}

// Header carries the `# yarn lockfile v1` marker so lockfile-any.ts's detectKind()
// routes on filename-and-content sniff to the classic parser. Two blank lines between
// header and body match real yarn v1 output byte-for-byte.
const HEADER = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n';

// Standard fake integrity hash — real yarn.lock ships sha512 base64 (88 chars).
const FAKE_INTEGRITY = `sha512-${'a'.repeat(88)}`;

function pkgName(i: number): string {
  return `pkg${i}`;
}

function buildWideSpecs(count: number): string {
  const parts: string[] = [];
  for (let i = 0; i < count; i++) {
    const name = pkgName(i);
    parts.push(
      `${name}@^1.0.0:\n` +
        `  version "1.0.0"\n` +
        `  resolved "https://registry.npmjs.org/${name}/-/${name}-1.0.0.tgz#0"\n` +
        `  integrity ${FAKE_INTEGRITY}`,
    );
  }
  return parts.join('\n\n');
}

function buildLongSpecList(count: number): string {
  // Single entry keyed by N comma-joined alias specs all pointing at the same package.
  // Real yarn.lock deduplicates aliases this way; count=1000 is intentionally beyond
  // anything the ecosystem produces in the wild.
  const aliases: string[] = [];
  for (let i = 0; i < count; i++) {
    aliases.push(`foo@^1.${i}.0`);
  }
  const key = aliases.join(', ');
  return (
    `${key}:\n` +
    `  version "1.0.0"\n` +
    `  resolved "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz#0"\n` +
    `  integrity ${FAKE_INTEGRITY}`
  );
}

function buildAliasChain(count: number): string {
  const parts: string[] = [];
  for (let i = 0; i < count; i++) {
    const name = pkgName(i);
    const nextName = i + 1 < count ? pkgName(i + 1) : null;
    const lines: string[] = [
      `${name}@^1.0.0:`,
      `  version "1.0.0"`,
      `  resolved "https://registry.npmjs.org/${name}/-/${name}-1.0.0.tgz#0"`,
      `  integrity ${FAKE_INTEGRITY}`,
    ];
    if (nextName) {
      lines.push('  dependencies:');
      lines.push(`    ${nextName} "^1.0.0"`);
    }
    parts.push(lines.join('\n'));
  }
  return parts.join('\n\n');
}

export const yarnClassicDeep: RobustnessGenerator<YarnClassicDeepParams> = {
  id: 'yarn-classic-deep',
  description:
    'yarn.lock v1 with pathological wide-specs / long-spec-list / alias-chain shapes.',
  format: 'yarn-classic',
  generate(seed, params): LockfileInput {
    // Seed unused today — output is fully determined by mode + scale. Kept in the
    // signature so future variants (e.g. randomizing package names to defeat parser
    // interning) can flip on without changing callers.
    void seed;
    if (!params) throw new Error('yarn-classic-deep: params required');
    const { mode, scale } = params;
    if (!Number.isInteger(scale) || scale < 0 || scale > 100_000) {
      throw new Error(
        `yarn-classic-deep: scale must be a non-negative integer <= 100000; got ${scale}`,
      );
    }
    let body: string;
    switch (mode) {
      case 'wide-specs':
        body = buildWideSpecs(scale);
        break;
      case 'long-spec-list':
        body = buildLongSpecList(scale);
        break;
      case 'alias-chain':
        body = buildAliasChain(scale);
        break;
      default: {
        // Exhaustiveness — any new mode must have a case here.
        const _exhaustive: never = mode;
        throw new Error(`yarn-classic-deep: unknown mode ${String(_exhaustive)}`);
      }
    }
    return {
      text: `${HEADER}${body}\n`,
      filename: 'yarn.lock',
      format: 'yarn-classic',
    };
  },
};
