/**
 * Metrics collector — the pipeline that turns "we ran the assurance suite" into the numbers
 * that show up in ASSURANCE.md's Metrics section.
 *
 * PACKET §4 contract: "Every number is regenerated by `pnpm assurance:report`; an
 * assurance-report-generated.test asserts it." That means:
 *   1. The generator (report/generator.ts) is a pure function of ReportInput.
 *   2. The CLI (report/cli.ts) is the impure wrapper — it must actually MEASURE things and
 *      hand a populated ReportInput to the generator.
 * This collector is the "measure things" step. It spawns vitest with the JSON reporter, groups
 * assertions by bucket (test/robustness/, test/evasion/, test/metamorphic/), and reports rates.
 *
 * # Design decisions
 *
 * ## Why subprocess, not in-process vitest?
 * The CLI is invoked as its own top-level `pnpm assurance:report` — it should NOT presume the
 * caller is already inside a vitest run. Spawning vitest --reporter=json is the honest way to
 * "run the harness once and report what happened". The subprocess writes JSON to a temp file
 * (--outputFile) which we then parse.
 *
 * ## Why exclude test/report/**?
 * The assurance-report-generated test spawns the CLI as a subprocess. If the CLI's collector
 * then ran test/report/ as part of the suite, the CLI would try to run itself — infinite
 * recursion, plus you'd fail the reproducibility check because the second nested run's
 * numbers would drift. test/report/ is also NOT a metric bucket — it's the generator's own
 * self-tests — so excluding it costs no measurement fidelity.
 *
 * ## Why graceful nulls for capability-map and differential-ledger?
 * Wave 1B-H (capability-map) and Wave 1B-I (differential-ledger) run on parallel branches.
 * This branch has to integrate cleanly regardless of the order the sibling branches land. So
 * the collector probes for `src/capability-map/index.ts` and `report/differential-ledger.json`
 * — missing → null, present → derived.
 *
 * ## Why null for empty buckets?
 * A bucket with zero tests hasn't been "measured" — it's absent, not zero. `null` maps to
 * "no data (tier not yet active)" in generator output; `0` would render as "0.0%", which is a
 * lie (implies we tried and everything failed). This matches the packet's honesty rule.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve as pathResolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

/** The numbers that show up in ASSURANCE.md's Metrics section. */
export interface MetricsSnapshot {
  /** Fraction 0..1 of robustness tests that passed, or null if the bucket is empty. */
  readonly robustnessPassRate: number | null;
  /** Fraction 0..1 of CAPABILITY-MAP sinks/entry-points covered by tests. Null if map is absent. */
  readonly enumeratedCoverage: number | null;
  /** Fraction 0..1 of evasion tests that caught the mutation. Null if bucket is empty. */
  readonly evasionCatchRate: number | null;
  /** Fraction 0..1 of metamorphic tests where the invariant held. Null if bucket is empty. */
  readonly metamorphicInvariance: number | null;
  /** Free-text summary of differential ledger. Null if ledger file is absent. */
  readonly differentialLedgerNote: string | null;
  /** Raw counts, for debugging + the honesty-note in the report. */
  readonly raw: {
    readonly testFiles: number;
    readonly testsPassed: number;
    readonly testsFailed: number;
    readonly testsSkipped: number;
  };
}

/** Bucketed counts we track per test-directory root. */
interface BucketCounts {
  passed: number;
  failed: number;
  total: number;
}

/** Path of this compiled file → resolve up to assurance/. */
function assuranceRoot(): string {
  // At runtime this is dist/metrics/collector.js, so we go up two levels to assurance/.
  return pathResolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
}

/**
 * Which bucket does a test file belong to? Vitest's `name` field is an absolute path to the
 * .test.ts file. We match on the test/<bucket>/ prefix relative to assurance/.
 */
function bucketOf(testFileAbs: string, root: string): string | null {
  const rel = pathResolve(testFileAbs).startsWith(root)
    ? pathResolve(testFileAbs).slice(root.length + 1)
    : testFileAbs;
  // rel now looks like "test/robustness/no-crash.test.ts" or "test/oracles/oracles.test.ts".
  // Vitest returns native absolute paths. Normalize after relativizing so the metric
  // buckets are identical on Windows development machines and Linux CI runners.
  const m = rel.replaceAll('\\', '/').match(/^test\/([^/]+)\//);
  return m ? m[1] : null;
}

/** null-safe rate: null when total is 0, else passed/total. */
function rateOrNull(counts: BucketCounts): number | null {
  return counts.total === 0 ? null : counts.passed / counts.total;
}

/**
 * Spawn vitest with the JSON reporter, parse the results, and bucket them.
 *
 * If the spawned vitest fails (any test fails), we STILL return a snapshot — the report is
 * supposed to reflect reality, and reality-with-failures is a lower pass-rate, not a crash.
 * The collector itself only throws if vitest didn't even produce a JSON file (a genuinely
 * broken toolchain, not just failing tests).
 */
export async function collectMetrics(): Promise<MetricsSnapshot> {
  const root = assuranceRoot();
  const suppliedReport = process.env.ASSURANCE_VITEST_JSON?.trim();
  const tmpDir = suppliedReport ? null : mkdtempSync(join(tmpdir(), 'assurance-metrics-'));
  const outFile = suppliedReport
    ? pathResolve(root, suppliedReport)
    : join(tmpDir!, 'vitest.json');

  // Path to vitest's CLI entry — we could also `node_modules/.bin/vitest` but going directly
  // through the .mjs is the same behavior with one fewer shim in the way.
  const vitestBin = pathResolve(root, 'node_modules', 'vitest', 'vitest.mjs');

  try {
    // Exclude test/report/** to prevent CLI-inside-CLI recursion when the
    // assurance-report-generated test spawns this CLI as a subprocess.
    // Also skip the "pretest" build hook — the caller is already built.
    if (!suppliedReport) {
      spawnSync(
        process.execPath, // node
        [
          vitestBin,
          'run',
          '--reporter=json',
          `--outputFile=${outFile}`,
          '--exclude',
          'test/report/**',
        ],
        {
          cwd: root,
          stdio: ['ignore', 'pipe', 'pipe'],
          // Vitest inherits NODE env; keep it minimal.
          env: { ...process.env },
          // No timeout at spawn level — vitest has its own internal timeouts (testTimeout in
          // vitest.config.ts). If the whole thing hangs, ctrl-C is the fix, not a race here.
        },
      );
    }

    if (!existsSync(outFile)) {
      throw new Error(
        `vitest did not produce ${outFile} — toolchain broken (expected JSON reporter output).`,
      );
    }

    const raw = JSON.parse(readFileSync(outFile, 'utf-8')) as {
      numTotalTests: number;
      numPassedTests: number;
      numFailedTests: number;
      numPendingTests: number;
      numTotalTestSuites: number;
      testResults: ReadonlyArray<{
        name: string;
        assertionResults: ReadonlyArray<{
          status: 'passed' | 'failed' | 'pending' | 'skipped' | 'todo';
        }>;
      }>;
    };

    // Bucket per top-level test directory.
    const buckets = new Map<string, BucketCounts>();
    for (const file of raw.testResults) {
      const bucket = bucketOf(file.name, root);
      if (!bucket) continue;
      const b =
        buckets.get(bucket) ??
        ({ passed: 0, failed: 0, total: 0 } as BucketCounts);
      for (const a of file.assertionResults) {
        // Skipped / pending / todo aren't counted in total — they aren't measurements.
        if (a.status === 'passed') {
          b.passed += 1;
          b.total += 1;
        } else if (a.status === 'failed') {
          b.failed += 1;
          b.total += 1;
        }
      }
      buckets.set(bucket, b);
    }

    const empty: BucketCounts = { passed: 0, failed: 0, total: 0 };

    // Enumerated coverage: if the CAPABILITY-MAP (Wave 1B-H) has landed, derive from it. The
    // measure is presence-based — "for each enumerated class, does at least one assurance
    // artifact (a completeness-vector transform) target it?" This is a FLOOR metric (packet
    // §7): "N/M classes covered" says nothing about whether every SINK in that class is
    // exercised, only that the class is on the assurance radar at all. A stronger metric
    // (per-sink coverage) is a future refinement.
    const capabilityMapIndex = pathResolve(root, 'src', 'capability-map', 'index.ts');
    const completenessVectorsIndex = pathResolve(root, 'src', 'completeness-vectors', 'index.ts');
    let enumeratedCoverage: number | null = null;
    if (existsSync(capabilityMapIndex) && existsSync(completenessVectorsIndex)) {
      try {
        // Dynamic-import the compiled dist so the collector doesn't couple to the source tree
        // at build time. Both are workspace-local ESM modules with stable `dist/` mirrors.
        const capModuleUrl = fileURLToPath(import.meta.url);
        const distRoot = pathResolve(dirname(capModuleUrl), '..');
        const capabilityMap = (await import(
          pathResolve(distRoot, 'capability-map', 'index.js')
        )) as {
          loadCapabilityMap: () => {
            classes: Record<string, { sinks: ReadonlyArray<{ id: string }> }>;
          };
          CAPABILITY_CLASS_IDS: readonly string[];
        };
        const completeness = (await import(
          pathResolve(distRoot, 'completeness-vectors', 'index.js')
        )) as {
          allTransforms: ReadonlyArray<{ targetClass: string }>;
        };
        const map = capabilityMap.loadCapabilityMap();
        // Every class present in the map (STARTUP's shape may include extensions like
        // fs-read / secret-read / integrity beyond the packet §3.5 canonical nine). We
        // count against the actual enumerated set, not against a hardcoded floor.
        const allClasses = new Set(Object.keys(map.classes));
        // A class is "covered" iff at least one transform targets it. targetClass values
        // like `code-execution` map straight into map.classes keys.
        const coveredClasses = new Set(
          completeness.allTransforms.map((t) => t.targetClass),
        );
        // Intersect: covered ∩ actually-enumerated. A transform pointing at a class the
        // map doesn't enumerate is off-target and doesn't count.
        const hits = [...coveredClasses].filter((c) => allClasses.has(c)).length;
        const total = allClasses.size;
        enumeratedCoverage = total === 0 ? null : hits / total;
      } catch {
        // Loading failed (unbuilt dist, shape drift, etc.) → stay null. Report will say "no
        // data", which is honest — we tried to measure and couldn't.
        enumeratedCoverage = null;
      }
    }

    // Differential-ledger note: read the file the differential subsystem produces at
    // assurance/report/differential-ledger.json. Every entry in the file's `deltas` array is
    // by construction already classified (that's what LedgerFile.deltas MEANS — see
    // src/differential/ledger.ts, where `classify()` is the only path into that array). The
    // separate `pending` array holds unclassified findings; if it's non-empty the ledger is
    // NOT clean (packet §5 P3 done-gate).
    const ledgerPath = pathResolve(root, 'report', 'differential-ledger.json');
    let differentialLedgerNote: string | null = null;
    if (existsSync(ledgerPath)) {
      try {
        const ledger = JSON.parse(readFileSync(ledgerPath, 'utf-8')) as {
          deltas?: ReadonlyArray<{ class?: string }>;
          pending?: ReadonlyArray<unknown>;
        };
        const deltas = ledger.deltas ?? [];
        const pending = ledger.pending ?? [];
        if (deltas.length === 0 && pending.length === 0) {
          differentialLedgerNote = '0 deltas';
        } else if (pending.length === 0) {
          differentialLedgerNote = `${deltas.length} deltas, all classified`;
        } else {
          differentialLedgerNote = `${deltas.length} classified, ${pending.length} PENDING (ledger not clean)`;
        }
      } catch {
        // Malformed ledger file → keep null; the report will show "no data" rather than lying.
        differentialLedgerNote = null;
      }
    }

    return {
      robustnessPassRate: rateOrNull(buckets.get('robustness') ?? empty),
      enumeratedCoverage,
      evasionCatchRate: rateOrNull(buckets.get('evasion') ?? empty),
      metamorphicInvariance: rateOrNull(buckets.get('metamorphic') ?? empty),
      differentialLedgerNote,
      raw: {
        testFiles: raw.testResults.length,
        testsPassed: raw.numPassedTests,
        testsFailed: raw.numFailedTests,
        testsSkipped: raw.numPendingTests,
      },
    };
  } finally {
    // Always clean up the temp dir; don't leak /tmp/assurance-metrics-* dirs on every run.
    if (tmpDir) {
      try {
        rmSync(tmpDir, { recursive: true, force: true });
      } catch {
        // Non-fatal — tmpfs cleanup is best-effort.
      }
    }
  }
}
