/**
 * `vetlock guard` — install a PATH shim so `npm install` / `pnpm add` /
 * `yarn add` route through `vetlock add` automatically.
 *
 * WHY:
 *   `vetlock add lodash@1.2.3` is the pre-install gate, but every muscle-memory
 *   `npm install lodash` bypasses it. `guard --install-shim` writes a small
 *   wrapper script to `~/.vetlock/bin/{npm,pnpm,yarn}` that intercepts
 *   install-family commands and re-invokes them through `vetlock add`. Other
 *   commands (`npm test`, `npm run …`, `pnpm ls`, `yarn build`) pass through
 *   to the real binary.
 *
 * FLOW (from a developer's POV):
 *   1. `vetlock guard --install-shim` — writes the shims + prints the exact
 *      PATH export line you need to add to your shell rc.
 *   2. Once PATH is set, `npm install evil-pkg` resolves the shim first,
 *      the shim sees `install evil-pkg` and re-invokes as
 *      `vetlock add evil-pkg --pm npm`.
 *   3. `vetlock add` runs the never-execute static gate. If it clears, it
 *      shells out to the REAL `npm install evil-pkg`. If it blocks, no
 *      `npm install` ever happens.
 *   4. Non-install commands (`npm test`) bypass the gate and go straight
 *      to the real binary. The shim detects them by inspecting argv[2].
 *   5. `VETLOCK_GUARD_BYPASS=1` env variable prevents recursion: when
 *      `vetlock add` shells out to `npm install`, it sets this so the shim
 *      does NOT try to re-gate.
 *
 * OPT-IN, REVERSIBLE:
 *   The shim only affects users who explicitly PATH-prepend `~/.vetlock/bin`.
 *   `vetlock guard --uninstall-shim` removes the shims. `vetlock guard --status`
 *   reports the state so you can audit.
 *
 * ALLOWLIST:
 *   `vetlock guard --allowlist add <pkg> --reason "…"` writes to
 *   `~/.vetlock/allowlist.json`. `vetlock add` reads this file and skips
 *   the static gate for allowlisted packages (still shells out to the real
 *   pm). Every entry MUST carry a human-readable reason string — the
 *   allowlist is meant to document trust decisions, not to be a silent
 *   escape hatch.
 */

import { promises as fs } from 'node:fs';
import * as fsSync from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import pc from 'picocolors';
import { vetlockUserDir, readAllowlist, type AllowlistEntry } from './add.js';

/** The three PMs we install shims for. */
const SHIM_PMS = ['npm', 'pnpm', 'yarn'] as const;
type ShimPm = typeof SHIM_PMS[number];

/** Install-family subcommands per PM that we want to gate. */
const INSTALL_SUBCOMMANDS: Record<ShimPm, ReadonlySet<string>> = {
  // npm install lodash / npm i lodash / npm add lodash (npm accepts `add` since v7)
  npm: new Set(['install', 'i', 'add']),
  // pnpm add lodash / pnpm install lodash / pnpm i lodash
  pnpm: new Set(['add', 'install', 'i']),
  // yarn add lodash / yarn install (bare)
  yarn: new Set(['add', 'install']),
};

export interface GuardCommandOptions {
  installShim?: boolean;
  uninstallShim?: boolean;
  status?: boolean;
  allowlistAction?: 'add' | 'list' | 'remove';
  allowlistPackage?: string;
  allowlistReason?: string;
  quiet?: boolean;
  /** For tests: override `~/.vetlock` path. */
  home?: string;
}

export interface GuardCommandResult {
  exitCode: number;
  /** Machine-readable summary of what happened. */
  action: 'install-shim' | 'uninstall-shim' | 'status' | 'allowlist' | 'usage-error';
  installedShims?: string[];
  removedShims?: string[];
  onPath?: Record<ShimPm, boolean>;
  allowlist?: AllowlistEntry[];
  message?: string;
}

/**
 * The shim script body. Small, portable, POSIX sh. Only depends on
 * `command -v` and `node` (which the developer already has, since npm
 * ships with it).
 *
 * Why a shell script and not a Node script:
 *   1. Portability — every install of every PM already runs on a POSIX shell.
 *   2. Startup latency — /bin/sh spins up in ~2ms; node ~40ms. This runs
 *      before EVERY `npm foo` so latency matters.
 *   3. Loop-safety — the shim needs to strip its own dir from PATH before
 *      exec'ing the real binary. A shell can do that in one line.
 *
 * The template placeholders `__PM_NAME__` and `__INSTALL_SET__` are replaced
 * per-PM at write time.
 */
const SHIM_TEMPLATE = `#!/bin/sh
# vetlock guard shim — DO NOT EDIT
# Auto-generated by \`vetlock guard --install-shim\`. Removing this file
# removes the shim; \`vetlock guard --uninstall-shim\` also removes it.
set -e

PM_NAME="__PM_NAME__"

# Recursion guard: when \`vetlock add\` calls the real PM, it sets this env.
# Without this the shim would loop.
if [ "\${VETLOCK_GUARD_BYPASS:-}" = "1" ]; then
  # Strip our shim dir from PATH so \`command -v\` finds the real pm.
  # We rely on the caller having exported VETLOCK_SHIM_DIR (set below when
  # we're launched via the shim template's own PATH manipulation), or fall
  # back to the standard install location.
  SHIM_DIR="\${VETLOCK_SHIM_DIR:-\$HOME/.vetlock/bin}"
  NEW_PATH=\$(printf '%s' "\$PATH" | awk -v d="\$SHIM_DIR" 'BEGIN{RS=":"; ORS=":"} \$0 != d { print }' | sed 's/:$//')
  export PATH="\$NEW_PATH"
  exec "\$PM_NAME" "\$@"
fi

# Detect subcommand — first non-flag argument.
subcmd=""
for a in "\$@"; do
  case "\$a" in
    -*) : ;;  # skip flags
    *) subcmd="\$a"; break ;;
  esac
done

# Is this an install-family subcommand?
is_install="0"
__INSTALL_SET__

if [ "\$is_install" = "1" ]; then
  # Extract the package spec — first non-flag arg AFTER the subcommand.
  shift_count=0
  seen_subcmd="0"
  spec=""
  for a in "\$@"; do
    shift_count=\$((shift_count+1))
    if [ "\$seen_subcmd" = "0" ]; then
      case "\$a" in
        -*) : ;;
        *) if [ "\$a" = "\$subcmd" ]; then seen_subcmd="1"; fi ;;
      esac
      continue
    fi
    case "\$a" in
      -*) : ;;
      *) spec="\$a"; break ;;
    esac
  done
  if [ -z "\$spec" ]; then
    # Bare \`npm install\` (reinstall everything) — pass through unmodified.
    # The gate can't reason about "everything the lockfile says"; that's
    # what \`vetlock scan\` / \`vetlock diff\` are for.
    exec_dir="\${VETLOCK_SHIM_DIR:-\$HOME/.vetlock/bin}"
    NEW_PATH=\$(printf '%s' "\$PATH" | awk -v d="\$exec_dir" 'BEGIN{RS=":"; ORS=":"} \$0 != d { print }' | sed 's/:$//')
    export PATH="\$NEW_PATH"
    exec "\$PM_NAME" "\$@"
  fi
  # Delegate to vetlock add. It will re-invoke the real PM after clearing.
  exec vetlock add "\$spec" --pm "\$PM_NAME"
fi

# Not an install-family subcommand — pass through to the real binary.
exec_dir="\${VETLOCK_SHIM_DIR:-\$HOME/.vetlock/bin}"
NEW_PATH=\$(printf '%s' "\$PATH" | awk -v d="\$exec_dir" 'BEGIN{RS=":"; ORS=":"} \$0 != d { print }' | sed 's/:$//')
export PATH="\$NEW_PATH"
exec "\$PM_NAME" "\$@"
`;

function renderShim(pm: ShimPm): string {
  const set = INSTALL_SUBCOMMANDS[pm];
  const caseClauses = Array.from(set).map((c) => `  ${JSON.stringify(c).slice(1, -1)}) is_install="1" ;;`);
  const scriptFragment = `case "$subcmd" in\n${caseClauses.join('\n')}\nesac\n`;
  return SHIM_TEMPLATE
    .replace(/__PM_NAME__/g, pm)
    .replace(/__INSTALL_SET__/g, scriptFragment);
}

export async function runGuardCommand(
  opts: GuardCommandOptions,
): Promise<GuardCommandResult> {
  const home = opts.home ?? vetlockUserDir();
  const binDir = path.join(home, 'bin');

  // Exactly one operation per invocation.
  const ops = [opts.installShim, opts.uninstallShim, opts.status, !!opts.allowlistAction]
    .filter(Boolean).length;
  if (ops !== 1) {
    printErr(opts, `vetlock guard: pass exactly one of --install-shim, --uninstall-shim, --status, --allowlist add|list|remove`);
    return { exitCode: 4, action: 'usage-error' };
  }

  if (opts.installShim) return await installShim(binDir, opts);
  if (opts.uninstallShim) return await uninstallShim(binDir, opts);
  if (opts.status) return await statusCheck(binDir, opts);
  if (opts.allowlistAction) return await allowlistCmd(home, opts);
  return { exitCode: 4, action: 'usage-error' };
}

async function installShim(
  binDir: string,
  opts: GuardCommandOptions,
): Promise<GuardCommandResult> {
  await fs.mkdir(binDir, { recursive: true });
  const installed: string[] = [];
  for (const pm of SHIM_PMS) {
    const shimPath = path.join(binDir, pm);
    await fs.writeFile(shimPath, renderShim(pm), 'utf8');
    // Executable bit (0o755) — otherwise the shim silently fails when PATH
    // finds it.
    await fs.chmod(shimPath, 0o755);
    installed.push(shimPath);
  }
  // Print the exact PATH export line the developer needs. We can't touch
  // shell rc files ourselves — that's a privilege the developer never gave us.
  printOut(opts, pc.green(`vetlock guard: installed shims for ${SHIM_PMS.join(', ')} in ${binDir}`));
  printOut(opts, '');
  printOut(opts, 'Add this to your ~/.zshrc / ~/.bashrc (whichever you use):');
  printOut(opts, '');
  printOut(opts, pc.cyan(`  export PATH="${binDir}:$PATH"`));
  printOut(opts, pc.cyan(`  export VETLOCK_SHIM_DIR="${binDir}"`));
  printOut(opts, '');
  printOut(opts, `Then open a new shell (or ${pc.bold('source')} the rc file).`);
  printOut(opts, `Verify with: ${pc.bold('vetlock guard --status')}`);
  return { exitCode: 0, action: 'install-shim', installedShims: installed };
}

async function uninstallShim(
  binDir: string,
  opts: GuardCommandOptions,
): Promise<GuardCommandResult> {
  const removed: string[] = [];
  for (const pm of SHIM_PMS) {
    const shimPath = path.join(binDir, pm);
    try {
      await fs.unlink(shimPath);
      removed.push(shimPath);
    } catch {
      // Missing shim = idempotent no-op.
    }
  }
  // If binDir is now empty, remove it — but only if empty.
  try {
    const contents = await fs.readdir(binDir);
    if (contents.length === 0) await fs.rmdir(binDir);
  } catch {
    // best-effort cleanup — a non-empty dir is fine
  }
  if (removed.length === 0) {
    printOut(opts, `vetlock guard: no shims to remove (nothing at ${binDir}).`);
  } else {
    printOut(opts, `vetlock guard: removed ${removed.length} shim${removed.length === 1 ? '' : 's'}.`);
    printOut(opts, `You may also want to remove ${pc.bold('export PATH=' + JSON.stringify(binDir) + ':$PATH')} from your shell rc.`);
  }
  return { exitCode: 0, action: 'uninstall-shim', removedShims: removed };
}

async function statusCheck(
  binDir: string,
  opts: GuardCommandOptions,
): Promise<GuardCommandResult> {
  const onPath: Record<ShimPm, boolean> = { npm: false, pnpm: false, yarn: false };
  const pathEntries = (process.env.PATH ?? '').split(path.delimiter);
  const shimDirNormalized = path.resolve(binDir);
  const shimDirBeforeRealPm = (pm: ShimPm): boolean => {
    // Which PATH entry provides `pm` first? If it's binDir, the shim wins.
    for (const entry of pathEntries) {
      if (!entry) continue;
      const candidate = path.join(entry, pm);
      if (fsSync.existsSync(candidate)) {
        return path.resolve(entry) === shimDirNormalized;
      }
    }
    return false;
  };
  for (const pm of SHIM_PMS) {
    const shimFile = path.join(binDir, pm);
    if (!fsSync.existsSync(shimFile)) {
      onPath[pm] = false;
      continue;
    }
    onPath[pm] = shimDirBeforeRealPm(pm);
  }
  const allActive = SHIM_PMS.every((pm) => onPath[pm]);
  const anyInstalled = SHIM_PMS.some((pm) => fsSync.existsSync(path.join(binDir, pm)));
  if (!anyInstalled) {
    printOut(opts, `vetlock guard: no shims installed. Run ${pc.bold('vetlock guard --install-shim')} to enable.`);
  } else {
    printOut(opts, 'vetlock guard status:');
    for (const pm of SHIM_PMS) {
      const shimFile = path.join(binDir, pm);
      const installed = fsSync.existsSync(shimFile);
      const active = onPath[pm];
      const label = active ? pc.green('active') : installed ? pc.yellow('installed but NOT on PATH ahead of real ' + pm) : pc.dim('not installed');
      printOut(opts, `  ${pm.padEnd(5)} ${label}`);
    }
    if (!allActive) {
      printOut(opts, '');
      printOut(opts, `To activate: add ${pc.cyan(`export PATH="${binDir}:$PATH"`)} to your shell rc.`);
    }
  }
  // Also try to detect which real PM binaries exist on the machine so the
  // developer sees the full picture.
  try {
    for (const pm of SHIM_PMS) {
      const real = execSync(`command -v ${pm} 2>/dev/null || true`, { encoding: 'utf8' }).trim();
      if (real) {
        printOut(opts, pc.dim(`  (${pm} resolves to: ${real})`));
      }
    }
  } catch {
    // command -v is a shell builtin so this rarely throws; ignore anyway
  }
  return { exitCode: 0, action: 'status', onPath };
}

async function allowlistCmd(
  home: string,
  opts: GuardCommandOptions,
): Promise<GuardCommandResult> {
  const allowlistPath = path.join(home, 'allowlist.json');
  if (opts.allowlistAction === 'list') {
    const list = await readAllowlistFromDir(home);
    if (list.length === 0) {
      printOut(opts, `vetlock guard: allowlist is empty (${allowlistPath}).`);
    } else {
      printOut(opts, `vetlock guard: allowlist has ${list.length} entr${list.length === 1 ? 'y' : 'ies'}:`);
      for (const e of list) {
        printOut(opts, `  ${pc.bold(e.package)}  ${pc.dim(`(${e.addedAt})`)}  — ${e.reason}`);
      }
    }
    return { exitCode: 0, action: 'allowlist', allowlist: list };
  }
  if (opts.allowlistAction === 'add') {
    if (!opts.allowlistPackage) {
      printErr(opts, `vetlock guard --allowlist add: missing <package> argument.`);
      return { exitCode: 4, action: 'usage-error' };
    }
    if (!opts.allowlistReason || opts.allowlistReason.trim().length < 3) {
      printErr(opts, `vetlock guard --allowlist add: --reason "…" is required (min 3 chars).`);
      printErr(opts, `The allowlist is meant to DOCUMENT trust decisions, not silently bypass the gate.`);
      return { exitCode: 4, action: 'usage-error' };
    }
    const existing = await readAllowlistFromDir(home);
    // Overwrite any prior entry with the same package name — the reason
    // string should track the current rationale.
    const now = new Date().toISOString();
    const entry: AllowlistEntry = {
      package: opts.allowlistPackage,
      reason: opts.allowlistReason.trim(),
      addedAt: now,
    };
    const next = existing.filter((e) => e.package !== opts.allowlistPackage).concat(entry);
    await fs.mkdir(home, { recursive: true });
    await fs.writeFile(allowlistPath, JSON.stringify(next, null, 2), 'utf8');
    printOut(opts, `vetlock guard: allowlisted ${pc.bold(opts.allowlistPackage)} — "${entry.reason}"`);
    return { exitCode: 0, action: 'allowlist', allowlist: next };
  }
  if (opts.allowlistAction === 'remove') {
    if (!opts.allowlistPackage) {
      printErr(opts, `vetlock guard --allowlist remove: missing <package> argument.`);
      return { exitCode: 4, action: 'usage-error' };
    }
    const existing = await readAllowlistFromDir(home);
    const next = existing.filter((e) => e.package !== opts.allowlistPackage);
    if (next.length === existing.length) {
      printOut(opts, `vetlock guard: ${opts.allowlistPackage} was not in the allowlist.`);
    } else {
      await fs.writeFile(allowlistPath, JSON.stringify(next, null, 2), 'utf8');
      printOut(opts, `vetlock guard: removed ${pc.bold(opts.allowlistPackage)} from the allowlist.`);
    }
    return { exitCode: 0, action: 'allowlist', allowlist: next };
  }
  return { exitCode: 4, action: 'usage-error' };
}

/**
 * Small wrapper around the shared `readAllowlist` from `commands/add.ts`
 * that respects the test-overridden `home`. `readAllowlist` uses
 * `vetlockUserDir()` (which honors `VETLOCK_HOME`); when tests pass a
 * different `home`, we need to read from that path directly.
 */
async function readAllowlistFromDir(home: string): Promise<AllowlistEntry[]> {
  // Delegate to the shared reader when the passed home matches what the
  // shared reader would use — cheaper and covered by add.ts tests.
  if (home === (process.env.VETLOCK_HOME ?? '')) {
    return await readAllowlist();
  }
  const p = path.join(home, 'allowlist.json');
  try {
    const raw = await fs.readFile(p, 'utf8');
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter(
      (e): e is AllowlistEntry =>
        typeof e === 'object' && e !== null &&
        typeof (e as AllowlistEntry).package === 'string' &&
        typeof (e as AllowlistEntry).reason === 'string' &&
        typeof (e as AllowlistEntry).addedAt === 'string',
    );
  } catch {
    return [];
  }
}

function printOut(opts: GuardCommandOptions, msg: string): void {
  if (opts.quiet) return;
  process.stdout.write(msg + '\n');
}

function printErr(opts: GuardCommandOptions, msg: string): void {
  if (opts.quiet) return;
  process.stderr.write(msg + '\n');
}
