/**
 * assurance-report-generated.test — the packet §4 named test.
 *
 * Packet contract: "Every number is regenerated by `pnpm assurance:report`;
 * assurance-report-generated.test asserts it."
 *
 * This test spawns the CLI (dist/report/cli.js) and asserts:
 *
 *   1. HONESTY — every metric line either shows a percentage (e.g. "100.0%") or the exact
 *      phrase "no data (tier not yet active)". NEVER "TODO", "undefined", "null", or an empty
 *      value. The report is the public trust artifact — a lie or a leaked placeholder in the
 *      Metrics section would be worse than any failing test.
 *
 *   2. STAMP MATCHES HEAD — the git SHA rendered in the stamp is the current HEAD of the
 *      repo. If they diverge, someone is regenerating the report at the wrong commit
 *      (e.g. after a rebase without re-running the CLI). This is a supply-chain trust
 *      property: the report claims to describe THIS commit.
 *
 *   3. REPRODUCIBILITY — running the CLI twice at the same commit produces the SAME Metrics
 *      section byte-for-byte. Only the "Generated:" timestamp naturally differs across runs;
 *      the numbers must not. This is the "reproducible from seed + git SHA" claim in the
 *      report's own header.
 *
 * These three assertions together are what makes the assurance report a signed artifact
 * rather than a rendered dashboard.
 *
 * # Why this test lives in test/report/
 *
 * The collector deliberately excludes `test/report/**` from its vitest subprocess — otherwise
 * the CLI (which spawns vitest) would end up running THIS test (which spawns the CLI) and
 * the recursion would never bottom out. So the report/generator tests only run when the
 * outer suite runs, never inside the CLI's own measurement pass.
 */

import { execSync, spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, resolve as pathResolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';

// This test file is at assurance/test/report/. Go up two levels to reach assurance/.
const ASSURANCE_ROOT = pathResolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
);
const CLI_PATH = pathResolve(ASSURANCE_ROOT, 'dist', 'report', 'cli.js');
const REPORT_PATH = pathResolve(ASSURANCE_ROOT, 'report', 'ASSURANCE.md');

/**
 * Run the CLI once, wait for it to finish, then return the ASSURANCE.md that was written.
 * The CLI itself spawns vitest for its measurement pass, so this is not instantaneous —
 * expect ~1-3 seconds per invocation on a warm cache.
 */
function runCliAndReadReport(): string {
  const result = spawnSync(process.execPath, [CLI_PATH], {
    cwd: ASSURANCE_ROOT,
    encoding: 'utf-8',
    // No env overrides — we want the CLI to see the same environment a user would.
  });
  if (result.status !== 0) {
    throw new Error(
      `CLI failed with status ${result.status}: ${result.stderr ?? '(no stderr)'}`,
    );
  }
  return readFileSync(REPORT_PATH, 'utf-8');
}

/**
 * Extract just the Metrics section — from "## Metrics" up to (but not including) the next
 * "## " heading. This is the invariant surface the report claims is reproducible; the Stamp
 * section deliberately isn't (it has a fresh timestamp on every run).
 */
function extractMetricsSection(report: string): string {
  const start = report.indexOf('## Metrics');
  if (start < 0) throw new Error('report has no ## Metrics section');
  // Find the NEXT "\n## " heading after the Metrics header.
  const rest = report.slice(start + 1);
  const nextHeading = rest.indexOf('\n## ');
  return nextHeading < 0 ? report.slice(start) : report.slice(start, start + 1 + nextHeading);
}

/** Grab the git SHA the CLI would have captured — the current HEAD of this worktree. */
function currentHeadSha(): string {
  return execSync('git rev-parse HEAD', {
    cwd: ASSURANCE_ROOT,
    encoding: 'utf-8',
  }).trim();
}

describe('assurance-report-generated (packet §4)', () => {
  it('regenerates ASSURANCE.md and every metric is either a percentage or the "no data" sentinel', () => {
    const report = runCliAndReadReport();
    const metrics = extractMetricsSection(report);

    // Extract every metric line — anything starting with "- **" under ## Metrics.
    const lines = metrics
      .split('\n')
      .filter((l) => l.startsWith('- **'));
    expect(lines.length).toBeGreaterThan(0);

    for (const line of lines) {
      // Every metric value must match ONE of:
      //   - percentage: NN.N% (e.g. "100.0%", "42.5%")
      //   - honest-null: "no data (tier not yet active)"
      //   - free-text ledger note: e.g. "3 deltas, all classified" (only for Differential deltas)
      const isPercentage = /\b\d+\.\d+%/.test(line);
      const isNoData = line.includes('no data (tier not yet active)');
      const isDifferentialFreeText = line.startsWith('- **Differential deltas:**');
      const ok = isPercentage || isNoData || isDifferentialFreeText;

      // Never a leaked placeholder — even the Differential free-text line should never contain
      // these tokens. If it does, someone shipped debug scaffolding to production.
      const hasPlaceholder =
        /\b(TODO|FIXME|XXX|undefined|\bnull\b|\[object Object\])\b/.test(line);
      expect(hasPlaceholder, `placeholder token in metric line: ${line}`).toBe(false);

      expect(ok, `metric line neither percentage nor "no data" sentinel: ${line}`).toBe(true);
    }
  });

  it('embeds the current git HEAD SHA in the stamp', () => {
    const report = runCliAndReadReport();
    const head = currentHeadSha();
    // The generator renders the SHA as inline code: `<sha>`. Assert exact substring.
    expect(report).toContain(`\`${head}\``);
  });

  it('produces byte-identical Metrics sections across two consecutive runs (reproducibility)', () => {
    // Run twice at the same commit, extract the Metrics section from each, and compare.
    // We intentionally do NOT compare full-report bytes — the Stamp's "Generated:" timestamp
    // is expected to advance between runs. Metrics is the "reproducible from seed + SHA" claim.
    const first = extractMetricsSection(runCliAndReadReport());
    const second = extractMetricsSection(runCliAndReadReport());
    expect(second).toBe(first);
  });
});
