/**
 * P4c: PyPI lockfile parser tests — the three formats we support.
 *
 * These tests PIN the interpretation choices called out in the header doc of
 * lockfile-pypi.ts (poetry v1/v2/v3 accept-all, uv v1-only, requirements.txt
 * accepts only `==` pins).
 */

import { describe, it, expect } from 'vitest';
import {
  parsePypiLockfileText,
  detectPypiKind,
  parseRequirementsText,
  parsePoetryLockText,
  parseUvLockText,
  canonicalizePypiName,
  normalizePypiHash,
  parseSimpleToml,
} from '../src/lockfile-pypi.js';
import { parseLockfileText, detectKind } from '../src/lockfile-any.js';

describe('canonicalizePypiName', () => {
  it('lowercases and normalises PEP-503 separators', () => {
    expect(canonicalizePypiName('Django')).toBe('django');
    expect(canonicalizePypiName('py-yaml')).toBe('py-yaml');
    expect(canonicalizePypiName('py_yaml')).toBe('py-yaml');
    expect(canonicalizePypiName('py.yaml')).toBe('py-yaml');
    expect(canonicalizePypiName('Zope.Interface')).toBe('zope-interface');
    expect(canonicalizePypiName('__future__')).toBe('-future-');
  });
});

describe('normalizePypiHash', () => {
  it('converts sha256:hex → sha256-hex', () => {
    expect(normalizePypiHash('sha256:abc123')).toBe('sha256-abc123');
    expect(normalizePypiHash('sha512:ffff')).toBe('sha512-ffff');
  });
  it('leaves already-SRI-shaped strings alone', () => {
    expect(normalizePypiHash('sha256-abc123')).toBe('sha256-abc123');
  });
});

describe('detectPypiKind', () => {
  it('uses filename hint when provided', () => {
    expect(detectPypiKind('anything', 'requirements.txt')).toBe('pypi-requirements');
    expect(detectPypiKind('anything', 'requirements-dev.txt')).toBe('pypi-requirements');
    expect(detectPypiKind('anything', 'poetry.lock')).toBe('pypi-poetry');
    expect(detectPypiKind('anything', 'uv.lock')).toBe('pypi-uv');
  });
  it('sniffs uv.lock from autogen header', () => {
    const t = `# This file was autogenerated by uv via the following command:\n#    uv lock\nversion = 1\n`;
    expect(detectPypiKind(t)).toBe('pypi-uv');
  });
  it('sniffs poetry.lock from [metadata] + lock-version', () => {
    const t = `[metadata]\nlock-version = "2.0"\npython-versions = ">=3.9"\n`;
    expect(detectPypiKind(t)).toBe('pypi-poetry');
  });
  it('sniffs requirements.txt from `==` pin lines', () => {
    expect(detectPypiKind('foo==1.2.3\nbar==4.5.6\n')).toBe('pypi-requirements');
  });
});

describe('parseRequirementsText', () => {
  it('parses simple pinned entries', () => {
    const g = parseRequirementsText(`
requests==2.31.0
urllib3==2.2.0
`);
    expect(g.byName.get('requests')?.length).toBe(1);
    expect(g.byName.get('urllib3')?.length).toBe(1);
    const req = g.nodes.get(g.byName.get('requests')![0]!)!;
    expect(req.name).toBe('requests');
    expect(req.version).toBe('2.31.0');
    // Root has both as direct deps
    const root = g.nodes.get('')!;
    expect(root.dependencies.length).toBe(2);
  });

  it('captures --hash entries as integrity', () => {
    const g = parseRequirementsText(
      `requests==2.31.0 --hash=sha256:aaaaa`,
    );
    const node = g.nodes.get(g.byName.get('requests')![0]!)!;
    expect(node.integrity).toBe('sha256-aaaaa');
  });

  it('handles continuation lines', () => {
    const g = parseRequirementsText(`
requests==2.31.0 \\
    --hash=sha256:aaaaa \\
    --hash=sha256:bbbbb
`);
    const node = g.nodes.get(g.byName.get('requests')![0]!)!;
    // First hash wins for integrity field.
    expect(node.integrity).toBe('sha256-aaaaa');
  });

  it('skips comments, blanks, and -r/-e/--flag lines', () => {
    const g = parseRequirementsText(`
# some comment
-r other-requirements.txt
--index-url https://example.com/simple
-e git+https://github.com/user/repo@main#egg=repo

requests==2.31.0
# trailing
`);
    expect(g.byName.get('requests')).toBeDefined();
    expect(g.byName.size).toBe(1);
  });

  it('strips extras from name: pkg[extra]==1.0', () => {
    const g = parseRequirementsText(`requests[socks]==2.31.0`);
    expect(g.byName.get('requests')).toBeDefined();
    expect(g.byName.get('requests[socks]')).toBeUndefined();
  });

  it('records unpinned entries with version="" (not silently dropped)', () => {
    const g = parseRequirementsText(`requests>=2.0\nurllib3~=1.26`);
    const req = g.nodes.get(g.byName.get('requests')![0]!)!;
    expect(req.version).toBe('');
    const url3 = g.nodes.get(g.byName.get('urllib3')![0]!)!;
    expect(url3.version).toBe('');
  });

  it('handles environment markers by ignoring them', () => {
    const g = parseRequirementsText(`typing-extensions==4.0.0; python_version<"3.11"`);
    // Canonicalised name uses '-'.
    expect(g.byName.get('typing-extensions')).toBeDefined();
  });
});

describe('parseSimpleToml', () => {
  it('parses simple key = value', () => {
    const doc = parseSimpleToml(`name = "foo"\nversion = 1\nlisted = true\n`);
    expect(doc.rootScalars.get('name')).toBe('foo');
    expect(doc.rootScalars.get('version')).toBe('1');
    expect(doc.rootScalars.get('listed')).toBe(true);
  });

  it('parses tables', () => {
    const doc = parseSimpleToml(`[metadata]\nlock-version = "2.0"\n`);
    expect(doc.tables.get('metadata')?.get('lock-version')).toBe('2.0');
  });

  it('parses arrays of tables', () => {
    const doc = parseSimpleToml(`
[[package]]
name = "foo"
version = "1.0.0"

[[package]]
name = "bar"
version = "2.0.0"
`);
    const packages = doc.arraysOfTables.get('package')!;
    expect(packages.length).toBe(2);
    expect(packages[0]!.get('name')).toBe('foo');
    expect(packages[1]!.get('name')).toBe('bar');
  });

  it('parses inline tables', () => {
    const doc = parseSimpleToml(`source = { url = "https://example.com", type = "url" }\n`);
    const src = doc.rootScalars.get('source') as Map<string, unknown>;
    expect(src.get('url')).toBe('https://example.com');
    expect(src.get('type')).toBe('url');
  });

  it('parses arrays of inline tables', () => {
    const doc = parseSimpleToml(`
[[package]]
name = "foo"
version = "1.0"
dependencies = [
    { name = "bar" },
    { name = "baz" },
]
`);
    const pkg = doc.arraysOfTables.get('package')![0]!;
    const deps = pkg.get('dependencies') as unknown[];
    expect(Array.isArray(deps)).toBe(true);
    expect(deps.length).toBe(2);
    expect((deps[0] as Map<string, unknown>).get('name')).toBe('bar');
  });

  it('handles dotted section headers under [[array]]', () => {
    const doc = parseSimpleToml(`
[[package]]
name = "foo"
version = "1.0"

[package.dependencies]
bar = ">=1.0"
`);
    const pkg = doc.arraysOfTables.get('package')![0]!;
    const deps = pkg.get('dependencies') as Map<string, unknown>;
    expect(deps).toBeInstanceOf(Map);
    expect(deps.get('bar')).toBe('>=1.0');
  });
});

describe('parsePoetryLockText', () => {
  it('parses a minimal poetry.lock with two packages', () => {
    const text = `
[[package]]
name = "requests"
version = "2.31.0"

[[package.dependencies]]
urllib3 = ">=1.21.1,<3"

[[package]]
name = "urllib3"
version = "2.0.0"

[metadata]
lock-version = "2.0"
`;
    // The poetry format uses [package.dependencies] as a subtable, NOT
    // [[package.dependencies]] as an array-of-tables. Rewrite:
    const cleanText = text.replace('[[package.dependencies]]', '[package.dependencies]');
    const g = parsePoetryLockText(cleanText);
    expect(g.byName.get('requests')).toBeDefined();
    expect(g.byName.get('urllib3')).toBeDefined();
    // requests should have urllib3 in its dependencies list.
    const reqKey = g.byName.get('requests')![0]!;
    const req = g.nodes.get(reqKey)!;
    expect(req.dependencies.length).toBeGreaterThan(0);
    const dep = g.nodes.get(req.dependencies[0]!)!;
    expect(dep.name).toBe('urllib3');
  });

  it('extracts hash from files table (poetry v1/v2)', () => {
    const text = `
[[package]]
name = "requests"
version = "2.31.0"

[[package.files]]
file = "requests-2.31.0-py3-none-any.whl"
hash = "sha256:aaaaa"

[metadata]
lock-version = "2.0"
`;
    const g = parsePoetryLockText(text);
    const node = g.nodes.get(g.byName.get('requests')![0]!)!;
    expect(node.integrity).toBe('sha256-aaaaa');
  });

  it('handles poetry v1 lock-version = "1.1"', () => {
    const text = `
[[package]]
name = "foo"
version = "1.0"

[metadata]
lock-version = "1.1"
`;
    const g = parsePoetryLockText(text);
    expect(g.byName.get('foo')).toBeDefined();
  });

  it('handles poetry v3 lock-version = "3.0"', () => {
    // As of packet-time (2026), poetry v3 uses "2.1" or "3.0" — both formats
    // are read identically by our parser.
    const text = `
[[package]]
name = "foo"
version = "1.0"

[metadata]
lock-version = "3.0"
`;
    const g = parsePoetryLockText(text);
    expect(g.byName.get('foo')).toBeDefined();
  });
});

describe('parseUvLockText', () => {
  it('parses a minimal uv.lock v1', () => {
    const text = `
version = 1
requires-python = ">=3.9"

[[package]]
name = "requests"
version = "2.31.0"

[[package.wheels]]
url = "https://files.pythonhosted.org/packages/requests-2.31.0-py3-none-any.whl"
hash = "sha256:abcdef"

[[package]]
name = "urllib3"
version = "2.0.0"
`;
    const g = parseUvLockText(text);
    expect(g.byName.get('requests')).toBeDefined();
    expect(g.byName.get('urllib3')).toBeDefined();
    const req = g.nodes.get(g.byName.get('requests')![0]!)!;
    expect(req.integrity).toBe('sha256-abcdef');
  });

  it('captures uv-style dependency arrays', () => {
    const text = `
version = 1

[[package]]
name = "requests"
version = "2.31.0"
dependencies = [
    { name = "urllib3" },
    { name = "certifi" },
]

[[package]]
name = "urllib3"
version = "2.0.0"

[[package]]
name = "certifi"
version = "2024.2.2"
`;
    const g = parseUvLockText(text);
    const req = g.nodes.get(g.byName.get('requests')![0]!)!;
    expect(req.dependencies.length).toBe(2);
  });

  it('rejects an unknown uv.lock version (fail loud)', () => {
    // This encodes our packet §STOP CONDITIONS interpretation: uv.lock v2 is
    // not yet defined; we refuse to guess.
    const text = `version = 999\n[[package]]\nname = "foo"\nversion = "1.0"\n`;
    expect(() => parseUvLockText(text)).toThrow(/unsupported uv\.lock version/);
  });
});

describe('parsePypiLockfileText dispatch', () => {
  it('routes requirements.txt', () => {
    const r = parsePypiLockfileText(`foo==1.0`, 'requirements.txt');
    expect(r.kind).toBe('pypi-requirements');
    expect(r.graph.byName.get('foo')).toBeDefined();
  });
  it('routes poetry.lock', () => {
    const r = parsePypiLockfileText(
      `[[package]]\nname = "foo"\nversion = "1.0"\n[metadata]\nlock-version = "2.0"\n`,
      'poetry.lock',
    );
    expect(r.kind).toBe('pypi-poetry');
  });
  it('routes uv.lock', () => {
    const r = parsePypiLockfileText(
      `version = 1\n[[package]]\nname = "foo"\nversion = "1.0"\n`,
      'uv.lock',
    );
    expect(r.kind).toBe('pypi-uv');
  });
});

describe('lockfile-any dispatcher integration (P4c)', () => {
  it('detectKind picks pypi-requirements for requirements.txt filename', () => {
    expect(detectKind('foo==1.0', 'requirements.txt')).toBe('pypi-requirements');
  });
  it('detectKind picks pypi-poetry for poetry.lock filename', () => {
    expect(detectKind('anything', 'poetry.lock')).toBe('pypi-poetry');
  });
  it('detectKind picks pypi-uv for uv.lock filename', () => {
    expect(detectKind('anything', 'uv.lock')).toBe('pypi-uv');
  });
  it('parseLockfileText returns ecosystem="pypi" for PyPI kinds', () => {
    const r = parseLockfileText(`foo==1.0`, 'requirements.txt');
    expect(r.ecosystem).toBe('pypi');
    expect(r.kind).toBe('pypi-requirements');
  });
  it('parseLockfileText returns ecosystem="npm" for npm-family kinds', () => {
    const r = parseLockfileText(
      JSON.stringify({
        name: 'root', version: '1.0.0', lockfileVersion: 3,
        packages: { '': { name: 'root', version: '1.0.0' } },
      }),
      'package-lock.json',
    );
    expect(r.ecosystem).toBe('npm');
    expect(r.kind).toBe('npm');
  });
});
