/**
 * P1-A · Lockfile-yarn end-to-end diff test.
 *
 * Parallel of lockfile-pnpm-diff.test.ts for the yarn ecosystem. Covers both
 * yarn classic (v1) and yarn berry lockfile formats through runDiff with a
 * fake cache. If the F1 dispatcher regresses (JSON.parse on `# yarn lockfile
 * v1` header, or on a berry `__metadata` block), these tests catch it.
 */

import { describe, it, expect } from 'vitest';
import type { Finding, PackageSnapshot, SnapshotPair } from '../src/finding.js';
import { runDiff } from '../src/engine.js';
import { SNAPSHOT_FORMAT_VERSION } from '../src/cache.js';

const FIXED_ISO = '2026-07-13T00:00:00.000Z';

function mkSnap(name: string, version: string, integrity: string): PackageSnapshot {
  return {
    name,
    version,
    integrity,
    manifest: { name, version },
    files: [],
    formatVersion: SNAPSHOT_FORMAT_VERSION,
    builtAt: FIXED_ISO,
  };
}

class FakeCache {
  public analyzed = new Set<string>();
  constructor(public store: Map<string, PackageSnapshot>) {}
  readonly dir = '/tmp/fake-cache';
  async get(integrity: string) {
    return this.store.get(integrity) ?? null;
  }
  async put(integrity: string, snap: PackageSnapshot) {
    this.store.set(integrity, snap);
    this.analyzed.add(`${snap.name}@${snap.version}`);
  }
}

// yarn.lock classic v1 — the shape yarn 1.x emits (still very common in the wild).
const YARN_CLASSIC_BEFORE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.20:
  version "4.17.20"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.20.tgz#b44a9b6297bcb698f1c51a3545a2b3b368d59c52"
  integrity sha512-PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==
`;

const YARN_CLASSIC_AFTER = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.20:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==
`;

// yarn berry v6 (yarn 3.x/4.x) shape.
const YARN_BERRY_BEFORE = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 10

"lodash@npm:^4.17.20":
  version: 4.17.20
  resolution: "lodash@npm:4.17.20"
  checksum: sha512-PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==
  languageName: node
  linkType: hard
`;

const YARN_BERRY_AFTER = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 10

"lodash@npm:^4.17.20":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==
  languageName: node
  linkType: hard
`;

const OLD_INT = 'sha512-PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==';
const NEW_INT = 'sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==';

function loadedCache(): FakeCache {
  return new FakeCache(new Map([
    [OLD_INT, mkSnap('lodash', '4.17.20', OLD_INT)],
    [NEW_INT, mkSnap('lodash', '4.17.21', NEW_INT)],
  ]));
}

function versionChangeDetector(pair: SnapshotPair, pkg: string): Finding[] {
  if (pair.old && pair.new && pair.old.version !== pair.new.version) {
    return [{
      detector: 'test.version-changed',
      category: 'META',
      package: pkg,
      from: pair.old.version,
      to: pair.new.version,
      direction: 'changed',
      severity: 'INFO',
      confidence: 'high',
      message: `${pair.old.version} → ${pair.new.version}`,
      evidence: [{ file: 'package.json', line: 1, snippet: pkg }],
      provenance: [],
    }];
  }
  return [];
}

describe('yarn.lock → runDiff end-to-end (P1-A · F1 regression guard)', () => {
  it('parses yarn classic v1 without a JSON.parse crash and surfaces the version-change', async () => {
    const result = await runDiff(YARN_CLASSIC_BEFORE, YARN_CLASSIC_AFTER, {
      runDetectors: versionChangeDetector,
      cache: loadedCache(),
      oldLockfilePath: 'yarn.lock',
      newLockfilePath: 'yarn.lock',
    });
    const change = result.findings.find(f => f.detector === 'test.version-changed');
    expect(change).toBeDefined();
    expect(change!.package).toBe('lodash');
    expect(change!.from).toBe('4.17.20');
    expect(change!.to).toBe('4.17.21');
  });

  it('parses yarn berry v6 without a JSON.parse crash and surfaces the version-change', async () => {
    const result = await runDiff(YARN_BERRY_BEFORE, YARN_BERRY_AFTER, {
      runDetectors: versionChangeDetector,
      cache: loadedCache(),
      oldLockfilePath: 'yarn.lock',
      newLockfilePath: 'yarn.lock',
    });
    const change = result.findings.find(f => f.detector === 'test.version-changed');
    expect(change).toBeDefined();
    expect(change!.package).toBe('lodash');
    expect(change!.to).toBe('4.17.21');
  });

  it('rejects a content-shape mismatch (yarn header on JSON body) gracefully', async () => {
    // Attacker: paste "# yarn lockfile v1" as a comment inside a JSON file.
    // parseLockfileText should either dispatch by filename (yarn → parser fails
    // on the JSON body it can't yaml-parse) or by content (attempts yarn parse
    // on JSON and fails). Either way: no CRASH, an error we can catch.
    const looksLikeYarnButIsJson = `# yarn lockfile v1\n{"lockfileVersion":3,"packages":{}}`;
    await expect(runDiff(looksLikeYarnButIsJson, looksLikeYarnButIsJson, {
      runDetectors: () => [],
      cache: new FakeCache(new Map()),
      oldLockfilePath: 'yarn.lock',
      newLockfilePath: 'yarn.lock',
    })).rejects.toThrow();  // A structured error is fine; a SyntaxError from JSON.parse would be an F1 regression.
  });
});
