import { describe, it, expect } from 'vitest';
import { parsePnpmLockText, parsePnpmPackageKey } from '../src/lockfile-pnpm.js';
import { parseYarnLockText, parseYarnAlias } from '../src/lockfile-yarn.js';
import { parseLockfileText, detectKind } from '../src/lockfile-any.js';

const PNPM_V9 = `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      chalk:
        specifier: ^5.3.0
        version: 5.3.1

packages:
  chalk@5.3.1:
    resolution: {integrity: sha512-oc0aXvB4hyzTh8FL2Yn43S8HbndhBQaSNKtRZG/BXKZmwCgxIfNKt6JHZHR3nZBqL+HKMr7bA6XyGYAA/qgLDA==, tarball: https://registry/chalk-5.3.1.tgz}

snapshots:
  chalk@5.3.1: {}
`;

const PNPM_V6 = `lockfileVersion: '6.0'

dependencies:
  chalk:
    specifier: ^5.3.0
    version: 5.3.1

packages:

  /chalk@5.3.1:
    resolution: {integrity: sha512-abc==, tarball: https://registry/chalk-5.3.1.tgz}
    dev: false
`;

const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


chalk@^5.3.0:
  version "5.3.1"
  resolved "https://registry/chalk-5.3.1.tgz#hash"
  integrity sha512-abc==

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry/lodash-4.17.21.tgz#hash2"
  integrity sha512-def==
  dependencies:
    debug "^4.0.0"

debug@^4.0.0:
  version "4.3.4"
  resolved "https://registry/debug-4.3.4.tgz#hash3"
  integrity sha512-ghi==
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"chalk@npm:^5.3.0":
  version: 5.3.1
  resolution: "chalk@npm:5.3.1"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/def
  languageName: node
  linkType: hard
`;

describe('pnpm-lock.yaml parser', () => {
  it('parses v9 format', () => {
    const g = parsePnpmLockText(PNPM_V9);
    expect(g.lockfileVersion).toBe(9);
    // Root has chalk as a dependency
    const root = g.nodes.get('');
    expect(root?.dependencies.length).toBeGreaterThan(0);
    // chalk node exists
    const chalkKey = g.byName.get('chalk')?.[0];
    expect(chalkKey).toBeDefined();
    const chalk = g.nodes.get(chalkKey!)!;
    expect(chalk.name).toBe('chalk');
    expect(chalk.version).toBe('5.3.1');
    expect(chalk.integrity).toMatch(/^sha512-/);
  });

  it('parses v6 format (leading-slash keys)', () => {
    const g = parsePnpmLockText(PNPM_V6);
    expect(g.lockfileVersion).toBe(6);
    const chalkKey = g.byName.get('chalk')?.[0];
    expect(chalkKey).toBeDefined();
    expect(g.nodes.get(chalkKey!)?.version).toBe('5.3.1');
  });

  it('rejects unsupported versions', () => {
    const src = `lockfileVersion: '3.0'\npackages: {}\n`;
    expect(() => parsePnpmLockText(src)).toThrow();
  });

  it('parsePnpmPackageKey handles scoped, versioned, peer-suffixed keys', () => {
    expect(parsePnpmPackageKey('/chalk@5.3.1')).toEqual({ name: 'chalk', version: '5.3.1' });
    expect(parsePnpmPackageKey('chalk@5.3.1')).toEqual({ name: 'chalk', version: '5.3.1' });
    expect(parsePnpmPackageKey('/@scope/pkg@1.0.0')).toEqual({ name: '@scope/pkg', version: '1.0.0' });
    expect(parsePnpmPackageKey('/pkg@1.0.0(peer@2.0.0)')).toEqual({ name: 'pkg', version: '1.0.0' });
  });
});

describe('yarn.lock parser', () => {
  it('parses classic v1 with dependencies', () => {
    const g = parseYarnLockText(YARN_CLASSIC);
    expect(g.lockfileVersion).toBe(1);
    // 3 packages: chalk, lodash, debug
    expect(g.byName.get('chalk')).toBeDefined();
    expect(g.byName.get('lodash')).toBeDefined();
    expect(g.byName.get('debug')).toBeDefined();
    // lodash depends on debug
    const lodashKey = g.byName.get('lodash')![0]!;
    const lodash = g.nodes.get(lodashKey)!;
    const debugKey = g.byName.get('debug')![0]!;
    expect(lodash.dependencies).toContain(debugKey);
  });

  it('parses yarn berry format', () => {
    const g = parseYarnLockText(YARN_BERRY);
    expect(g.lockfileVersion).toBe(6);
    expect(g.byName.get('chalk')).toBeDefined();
    expect(g.byName.get('lodash')).toBeDefined();
    const chalkKey = g.byName.get('chalk')![0]!;
    expect(g.nodes.get(chalkKey)?.version).toBe('5.3.1');
  });

  it('parseYarnAlias handles scoped and berry-style aliases', () => {
    expect(parseYarnAlias('foo@^1.0.0')).toEqual({ name: 'foo', spec: '^1.0.0' });
    expect(parseYarnAlias('@scope/foo@^1.0.0')).toEqual({ name: '@scope/foo', spec: '^1.0.0' });
    expect(parseYarnAlias('foo@npm:^1.0.0')).toEqual({ name: 'foo', spec: 'npm:^1.0.0' });
  });
});

describe('parseLockfileText — universal dispatcher', () => {
  it('detects npm from filename', () => {
    expect(detectKind('{"lockfileVersion":3,"packages":{}}', 'package-lock.json')).toBe('npm');
  });

  it('detects pnpm from filename', () => {
    expect(detectKind(PNPM_V9, 'pnpm-lock.yaml')).toBe('pnpm');
  });

  it('detects yarn classic vs berry from content', () => {
    expect(detectKind(YARN_CLASSIC, 'yarn.lock')).toBe('yarn-classic');
    expect(detectKind(YARN_BERRY, 'yarn.lock')).toBe('yarn-berry');
  });

  it('routes to the correct parser and returns a LockGraph', () => {
    const r = parseLockfileText(YARN_CLASSIC, 'yarn.lock');
    expect(r.kind).toBe('yarn-classic');
    expect(r.graph.byName.get('chalk')).toBeDefined();
  });

  it('detects npm from JSON content without filename', () => {
    const r = parseLockfileText(
      '{"name":"a","version":"1.0.0","lockfileVersion":3,"packages":{"":{"name":"a","version":"1.0.0"}}}',
    );
    expect(r.kind).toBe('npm');
  });
});
