/**
 * P1-E follow-up · REDTEAM N6 regression guard.
 *
 * N6 attack shape: a malicious dep is reachable ONLY via a peerDependencies
 * edge (not `dependencies` or `optionalDependencies`). Before the fix, both
 * the pnpm and yarn parsers merged only `dependencies` and
 * `optionalDependencies` into the graph — so the malicious dep had no parent
 * in the LockGraph, no provenance path from root, and no `rollupByDirect`
 * attribution. Renderers dropped it from the "impact by direct dependency"
 * view entirely.
 *
 * Fix: merge `peerDependencies` alongside `dependencies` and
 * `optionalDependencies` in both parsers.
 */

import { describe, it, expect } from 'vitest';
import { parsePnpmLockText } from '../../core/src/lockfile-pnpm.js';
import { parseYarnLockText } from '../../core/src/lockfile-yarn.js';

describe('REDTEAM N6 — peerDependencies must be merged into the graph', () => {
  it('pnpm-lock.yaml: peer-only edge produces a graph edge (parent → peer child)', () => {
    // Parent package `host` declares only a peer dep `evil`; no regular or
    // optional dep. Before the fix, `evil` was in the packages: map but
    // NOT in `host.dependencies` — so any downstream traversal from root
    // → host → evil was structurally impossible.
    const text = `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      host:
        specifier: ^1.0.0
        version: 1.0.0

packages:
  host@1.0.0:
    resolution:
      integrity: sha512-hostAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    peerDependencies:
      evil: 1.0.0
  evil@1.0.0:
    resolution:
      integrity: sha512-evilAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

snapshots:
  host@1.0.0:
    peerDependencies:
      evil: 1.0.0
  evil@1.0.0: {}
`;
    const graph = parsePnpmLockText(text);
    const hostKey = [...graph.byName.get('host') ?? []][0];
    const evilKey = [...graph.byName.get('evil') ?? []][0];
    expect(hostKey, 'host node exists').toBeDefined();
    expect(evilKey, 'evil node exists').toBeDefined();
    const host = graph.nodes.get(hostKey!)!;
    expect(host.dependencies, 'host must have evil as a child via peer edge').toContain(evilKey);
  });

  it('yarn.lock (classic v1): peer-only edge produces a graph edge', () => {
    // Yarn classic writes peerDependencies at the top level of an entry;
    // same underlying attack shape.
    const text = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


host@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/host/-/host-1.0.0.tgz#dead"
  integrity sha512-hostAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
  peerDependencies:
    evil "1.0.0"

evil@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/evil/-/evil-1.0.0.tgz#beef"
  integrity sha512-evilAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
`;
    const graph = parseYarnLockText(text);
    const hostKey = [...graph.byName.get('host') ?? []][0];
    const evilKey = [...graph.byName.get('evil') ?? []][0];
    expect(hostKey, 'host node exists').toBeDefined();
    expect(evilKey, 'evil node exists').toBeDefined();
    const host = graph.nodes.get(hostKey!)!;
    expect(host.dependencies, 'host must have evil as a child via peer edge').toContain(evilKey);
  });
});
