/**
 * PyPI ecosystem lockfile parser (P4c — ADR 0009 EcosystemAdapter).
 *
 * Handles three Python lockfile formats via a single `parsePypiLockfileText`
 * dispatcher:
 *
 *   1. `requirements.txt` — pip-freeze style:
 *        pkg==1.2.3
 *        pkg==1.2.3 --hash=sha256:...
 *        # comment lines, blank lines
 *        Only fully-pinned (`==`) entries are consumed. Ranges (`>=`, `~=`),
 *        editable installs (`-e`), and direct URL refs are recorded with
 *        version="" so downstream can flag them as non-pinned.
 *
 *   2. `poetry.lock` — TOML v1/v2/v3. Package table entries:
 *        [[package]]
 *        name = "foo"
 *        version = "1.2.3"
 *        [[package.dependencies]]   OR   [package.dependencies]
 *          bar = ">=1.0"
 *        [[package.files]]
 *          {file = "foo-1.2.3-py3-none-any.whl", hash = "sha256:..."}
 *
 *   3. `uv.lock` — TOML shaped like poetry but with a `[[package]]` array and
 *        `dependencies = [{name = "bar"}, ...]` shape (uv >= 0.4).
 *
 * All three converge on the shared `LockGraph` shape from `lockfile.ts`. We
 * synthesize node keys as `pypi/<name>` (and disambiguate collisions with
 * `@version` / `#N` suffixes, mirroring the yarn parser). Integrity strings
 * are stored in the PyPI SRI-adjacent form `sha256-<hex>` (or `sha512-<hex>`)
 * — the S10 tripwire treats them as opaque tokens, so this alternate hash
 * scheme still works for tamper detection between two same-version snapshots.
 *
 * DOC-COMMENT INTERPRETATION CHOICES (packet §STOP CONDITIONS):
 *   - `poetry.lock` v1 (`metadata.lock-version = "1.1"`) and v2 (`"2.0"`)
 *     both use `[[package]]` arrays; we treat them identically. Older v1
 *     without a lock-version field is rejected with a clear error.
 *   - `uv.lock` v1 (`version = 1`) is what uv 0.4-0.5 emits. The uv format
 *     is not yet fully stable — we PIN to v1 and reject unknown versions
 *     rather than silently misinterpret. Tests below encode this choice.
 *   - `requirements.txt` has no version field; we consume the file text
 *     directly with no shape-check beyond "at least one `==` line".
 */

import type { LockGraph, LockNode } from './lockfile.js';
import { UnsupportedLockfileError } from './lockfile.js';

/** Result of parsing a PyPI-family lockfile; kind distinguishes downstream policy. */
export type PypiLockfileKind = 'pypi-requirements' | 'pypi-poetry' | 'pypi-uv';

export interface PypiDetectionResult {
  kind: PypiLockfileKind;
  graph: LockGraph;
}

/**
 * Auto-detect + parse a PyPI-family lockfile.
 *
 * Detection order: filename hint (strongest signal), then content shape:
 *   - starts with `# This file is autogenerated by uv` OR `version = ...` at
 *     top level of TOML + a `[[package]]` block → uv.lock
 *   - `[metadata]` + `lock-version` present in TOML → poetry.lock
 *   - matches `<pkg>==<ver>` on any line → requirements.txt
 */
export function parsePypiLockfileText(text: string, filename?: string): PypiDetectionResult {
  const kind = detectPypiKind(text, filename);
  switch (kind) {
    case 'pypi-requirements':
      return { kind, graph: parseRequirementsText(text) };
    case 'pypi-poetry':
      return { kind, graph: parsePoetryLockText(text) };
    case 'pypi-uv':
      return { kind, graph: parseUvLockText(text) };
    default:
      throw new UnsupportedLockfileError('unable to detect PyPI lockfile format');
  }
}

export function detectPypiKind(text: string, filename?: string): PypiLockfileKind {
  if (filename) {
    const base = filename.split(/[\\/]/).pop() ?? '';
    if (base === 'requirements.txt' || /^requirements[-.\w]*\.txt$/.test(base)) {
      return 'pypi-requirements';
    }
    if (base === 'poetry.lock') return 'pypi-poetry';
    if (base === 'uv.lock') return 'pypi-uv';
  }
  // Content sniff. uv.lock has a distinct autogen header comment; poetry.lock
  // has `[metadata]` + `lock-version`. Otherwise fall through to requirements.
  if (/# This file was autogenerated by uv/i.test(text) || /# This file is autogenerated by uv/i.test(text)) {
    return 'pypi-uv';
  }
  if (/^\[metadata\][\s\S]*lock-version\s*=/m.test(text)) return 'pypi-poetry';
  if (/^\[\[package\]\]/m.test(text) && /^\s*version\s*=\s*\d/m.test(text)) {
    // Bare `version = N` at top-level of a TOML with package array →
    // more likely uv than poetry (poetry has lock-version, not version).
    return 'pypi-uv';
  }
  if (/^[A-Za-z0-9_.-]+\s*==\s*[\w.+-]+/m.test(text)) return 'pypi-requirements';
  throw new UnsupportedLockfileError('could not detect PyPI lockfile format from content');
}

// ---------- requirements.txt -----------------------------------------------

/**
 * Parse pip-freeze-style requirements.
 *
 * Recognises:
 *   pkg==1.2.3
 *   pkg==1.2.3    # trailing comment
 *   pkg==1.2.3 \
 *       --hash=sha256:abcdef...
 *   pkg==1.2.3;python_version<"3.9"   # marker — kept, marker ignored
 *
 * NOT recognised as pinned (recorded with version="" so downstream can flag):
 *   pkg>=1.0
 *   pkg~=1.0
 *   -e git+https://...
 *   ./local-package
 *
 * Comments (`# ...`), blank lines, and `-r otherfile.txt` are skipped.
 */
export function parseRequirementsText(text: string): LockGraph {
  // Join continuation lines (`\` at EOL).
  const joined = text.replace(/\\\r?\n/g, ' ');

  const nodes = new Map<string, LockNode>();
  const byName = new Map<string, string[]>();

  // Root node — requirements.txt has no name/version metadata of its own.
  nodes.set('', {
    key: '',
    name: '',
    version: '',
    integrity: '',
    resolved: null,
    dependencies: [],
  });
  const rootNode = nodes.get('')!;

  for (const rawLine of joined.split('\n')) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    // Strip inline comment (# preceded by whitespace)
    line = line.replace(/\s+#.*$/, '').trim();
    if (!line) continue;
    // Skip options / includes / editable installs / URL installs we can't pin.
    if (line.startsWith('-')) continue; // -r, -e, --hash on its own line, --index-url, etc.

    const parsed = parseRequirementLine(line);
    if (!parsed) continue;
    const { name, version, integrity } = parsed;
    const canonicalName = canonicalizePypiName(name);
    let key = `pypi/${canonicalName}`;
    if (nodes.has(key)) key = `${key}@${version}`;
    while (nodes.has(key)) key = `${key}#${nodes.size}`;

    nodes.set(key, {
      key,
      name: canonicalName,
      version,
      integrity,
      resolved: null,
      dependencies: [],
    });
    (byName.get(canonicalName) ?? byName.set(canonicalName, []).get(canonicalName)!).push(key);
    rootNode.dependencies.push(key);
  }

  rootNode.dependencies = [...new Set(rootNode.dependencies)];

  return {
    lockfileVersion: 0, // requirements.txt has no format version
    rootName: '',
    rootVersion: '',
    nodes,
    byName,
    workspaceLinks: [],
    npmAliases: [],
  };
}

interface ParsedRequirement {
  name: string;
  version: string;
  integrity: string;
}

/**
 * Parse a single requirement line. Returns null when we can't extract at
 * least a name.  We intentionally accept name-only (version="") lines so
 * downstream analyses can flag unpinned deps.
 */
function parseRequirementLine(line: string): ParsedRequirement | null {
  // Split off environment markers `; python_version<"3.9"`.
  const semiIdx = line.indexOf(';');
  const bareSpec = (semiIdx === -1 ? line : line.slice(0, semiIdx)).trim();

  // Extract hashes (may appear as `--hash=sha256:xxx --hash=sha256:yyy`)
  const hashes: string[] = [];
  const withoutHashes = bareSpec.replace(/--hash=([a-z0-9]+):([A-Fa-f0-9]+)/g, (_, algo, hex) => {
    hashes.push(`${algo}-${hex}`);
    return '';
  }).trim();

  // Now `withoutHashes` is a spec like `pkg==1.2.3` or `pkg>=1.0` or `pkg`.
  const specMatch = withoutHashes.match(/^([A-Za-z0-9_.\-[\]]+)\s*(==|>=|<=|~=|!=|>|<|===)?\s*([\w.+-]*)?/);
  if (!specMatch) return null;
  const rawName = specMatch[1]!;
  const op = specMatch[2] ?? '';
  const version = op === '==' ? (specMatch[3] ?? '') : '';
  // strip extras `pkg[extra]` — the pip resolver treats the base name as identity
  const name = rawName.replace(/\[.*?\]$/, '');
  if (!name) return null;

  // Use the FIRST hash as integrity (multi-hash entries record only one — we
  // preserve the raw value shape `<algo>-<hex>` so the S10 tripwire compares
  // like-for-like).
  const integrity = hashes[0] ?? '';
  return { name, version, integrity };
}

// ---------- poetry.lock / uv.lock (TOML) -----------------------------------

/**
 * Parse a poetry.lock file (v1 or v2). Returns a LockGraph.
 *
 * We use a small purpose-built TOML lexer — we don't want to add a heavyweight
 * TOML dependency for what is basically "extract every [[package]] block and
 * its scalar fields." The lexer is intentionally NOT a full TOML parser: it
 * handles the subset poetry/uv actually emit (arrays of tables, key = value,
 * inline tables, arrays of inline tables). Anything else falls through as
 * an unrecognised line and is ignored.
 *
 * If a `metadata.lock-version` is present, we accept "1.1", "2.0", and "3.0"
 * — the format has been backward-compatible enough that our slice reads
 * them all identically.
 */
export function parsePoetryLockText(text: string): LockGraph {
  const doc = parseSimpleToml(text);
  const meta = doc.tables.get('metadata');
  const lockVersion = meta?.get('lock-version');
  if (lockVersion !== undefined) {
    const v = typeof lockVersion === 'string' ? lockVersion : String(lockVersion);
    if (!/^(1\.[01]|2\.[01]|3\.[01])$/.test(v)) {
      // Not a hard error — we can still try, but note it. Poetry lock-version
      // strings are conservative; unexpected values suggest a future format
      // we haven't validated against.
      // Fall through: attempt parse but keep a debug breadcrumb.
    }
  }

  const packageTables = doc.arraysOfTables.get('package') ?? [];
  return buildPypiGraphFromTomlPackages(packageTables, 'poetry');
}

/**
 * Parse a uv.lock file. Returns a LockGraph.
 *
 * Format reference: https://docs.astral.sh/uv/reference/settings/#lockfile
 *
 * uv.lock v1 top-level shape:
 *   version = 1
 *   requires-python = ">=3.9"
 *   [[package]]
 *   name = "..."
 *   version = "..."
 *   source = { registry = "https://pypi.org/simple" }
 *   dependencies = [
 *     { name = "other-pkg" },
 *     { name = "other-pkg", extra = "..." },
 *   ]
 *   [[package.wheels]]
 *   url = "..."
 *   hash = "sha256:..."
 *
 * We PIN to `version = 1` and refuse unknown versions rather than
 * misinterpret — the format is young and we prefer failing loud.
 */
export function parseUvLockText(text: string): LockGraph {
  const doc = parseSimpleToml(text);
  const topVer = doc.rootScalars.get('version');
  if (topVer !== undefined && Number(topVer) !== 1) {
    throw new UnsupportedLockfileError(
      `unsupported uv.lock version ${topVer} — vetlock recognises v1 only`,
    );
  }
  const packageTables = doc.arraysOfTables.get('package') ?? [];
  return buildPypiGraphFromTomlPackages(packageTables, 'uv');
}

/**
 * Common builder: turn an array of `[[package]]` tables (parsed from poetry
 * or uv) into a LockGraph. Handles both:
 *   - poetry's `dependencies = { name = ">=1.0" }` inline table
 *   - poetry's `[package.dependencies]` subtable
 *   - uv's `dependencies = [{ name = "other" }, ...]` array of inline tables
 */
function buildPypiGraphFromTomlPackages(
  packages: Array<Map<string, unknown>>,
  variant: 'poetry' | 'uv',
): LockGraph {
  const nodes = new Map<string, LockNode>();
  const byName = new Map<string, string[]>();

  // Root
  nodes.set('', {
    key: '',
    name: '',
    version: '',
    integrity: '',
    resolved: null,
    dependencies: [],
  });

  // First pass — create nodes
  const depsByNodeKey = new Map<string, string[]>();
  for (const tbl of packages) {
    const rawName = asString(tbl.get('name'));
    if (!rawName) continue;
    const name = canonicalizePypiName(rawName);
    const version = asString(tbl.get('version')) ?? '';

    let key = `pypi/${name}`;
    if (nodes.has(key)) key = `${key}@${version}`;
    while (nodes.has(key)) key = `${key}#${nodes.size}`;

    // Integrity — poetry's files table entries look like `{file = "...", hash = "sha256:..."}`;
    // uv's wheels/sdist entries have `hash = "sha256:..."`. We take the FIRST hash we find and
    // convert to SRI-adjacent form `sha256-<hex>`.
    const integrity = firstPypiHash(tbl, variant);

    // Resolved: prefer explicit URL fields.
    const resolved =
      asString(tbl.get('url')) ??
      (extractPoetrySourceUrl(tbl.get('source'))) ??
      null;

    nodes.set(key, {
      key,
      name,
      version,
      integrity,
      resolved,
      dependencies: [],
    });
    (byName.get(name) ?? byName.set(name, []).get(name)!).push(key);

    // Collect the dependency names (resolution deferred until all nodes exist).
    const depNames = extractPypiDepNames(tbl.get('dependencies'), variant);
    if (depNames.length > 0) depsByNodeKey.set(key, depNames);
  }

  // Second pass — wire dependencies. First installed occurrence wins for name→key.
  for (const [nodeKey, depNames] of depsByNodeKey) {
    const node = nodes.get(nodeKey);
    if (!node) continue;
    for (const depName of depNames) {
      const canonical = canonicalizePypiName(depName);
      const dks = byName.get(canonical) ?? [];
      if (dks[0]) node.dependencies.push(dks[0]);
    }
    node.dependencies = [...new Set(node.dependencies)];
  }

  return {
    lockfileVersion: variant === 'poetry' ? 2 : 1,
    rootName: '',
    rootVersion: '',
    nodes,
    byName,
    workspaceLinks: [],
    npmAliases: [],
  };
}

/**
 * Extract dependency NAMES from either poetry-shape (map of name→spec) or
 * uv-shape (array of inline tables with `name` field).
 *
 * The uv shape reaches us as `Array<Map<string,unknown>>` because our TOML
 * lexer represents inline tables as Maps; the poetry shape reaches us as a
 * `Map<name, spec>` from a `[package.dependencies]` sub-table.
 */
function extractPypiDepNames(deps: unknown, variant: 'poetry' | 'uv'): string[] {
  const out: string[] = [];
  if (!deps) return out;
  if (variant === 'uv' && Array.isArray(deps)) {
    for (const entry of deps) {
      if (entry instanceof Map) {
        const name = entry.get('name');
        if (typeof name === 'string' && name) out.push(name);
      } else if (entry && typeof entry === 'object') {
        const name = (entry as { name?: unknown }).name;
        if (typeof name === 'string' && name) out.push(name);
      }
    }
    return out;
  }
  if (deps instanceof Map) {
    for (const [k] of deps) out.push(k);
    return out;
  }
  return out;
}

/** Get the first hash-value from a poetry or uv package table. */
function firstPypiHash(tbl: Map<string, unknown>, variant: 'poetry' | 'uv'): string {
  // Poetry: `[[package.files]]` (array-of-tables via dotted header, stored as
  // Array<Map>) OR `files = [{...}, ...]` inline (Array<Map|object>).
  if (variant === 'poetry') {
    const files = tbl.get('files');
    if (Array.isArray(files)) {
      for (const f of files) {
        const hash = readHashField(f);
        if (hash) return normalizePypiHash(hash);
      }
    }
  }
  // uv shape (also fallback for poetry entries without a `files` list): the
  // hash appears directly on inline tables in `wheels` / `sdist` sub-arrays.
  for (const subKey of ['wheels', 'sdist']) {
    const sub = tbl.get(subKey);
    if (Array.isArray(sub)) {
      for (const s of sub) {
        const hash = readHashField(s);
        if (hash) return normalizePypiHash(hash);
      }
    } else if (sub && typeof sub === 'object' && !(sub instanceof Map)) {
      const hash = (sub as { hash?: unknown }).hash;
      if (typeof hash === 'string') return normalizePypiHash(hash);
    }
  }
  // Also try top-level `hash` (some minimal test fixtures use this)
  const topHash = tbl.get('hash');
  if (typeof topHash === 'string') return normalizePypiHash(topHash);
  return '';
}

/** Read a `hash` field from an entry that may be a Map (from `[[header]]` shape) or a plain object (from inline `{...}`). */
function readHashField(entry: unknown): string | null {
  if (!entry) return null;
  if (entry instanceof Map) {
    const h = entry.get('hash');
    return typeof h === 'string' ? h : null;
  }
  if (typeof entry === 'object') {
    const h = (entry as { hash?: unknown }).hash;
    return typeof h === 'string' ? h : null;
  }
  return null;
}

/** poetry writes `source = { url = "...", type = "url" }` for non-registry sources. */
function extractPoetrySourceUrl(source: unknown): string | null {
  if (!source || typeof source !== 'object' || source instanceof Map) {
    if (source instanceof Map) {
      const u = source.get('url');
      return typeof u === 'string' ? u : null;
    }
    return null;
  }
  const u = (source as { url?: unknown }).url;
  return typeof u === 'string' ? u : null;
}

/**
 * PyPI package names are case-insensitive and treat `_` / `-` / `.` as
 * equivalent (PEP 503 normalisation).  Normalise so downstream detectors
 * that look up by name agree.
 */
export function canonicalizePypiName(name: string): string {
  return name.toLowerCase().replace(/[-_.]+/g, '-');
}

/**
 * Convert a PyPI-style hash (`sha256:<hex>`) into the SRI-shaped form
 * (`sha256-<hex>`) so the S10 same-version-tamper tripwire compares like
 * strings across ecosystems.  We keep hex encoding (not base64) — the
 * tripwire only asks whether the string is DIFFERENT between snapshots, so
 * the exact encoding is opaque to it.
 */
export function normalizePypiHash(raw: string): string {
  const m = raw.match(/^(sha\d+):([A-Fa-f0-9]+)$/);
  if (!m) return raw;
  return `${m[1]}-${m[2]}`;
}

function asString(v: unknown): string | undefined {
  return typeof v === 'string' ? v : undefined;
}

// ---------- Minimal TOML lexer ---------------------------------------------

/**
 * Purpose-built TOML subset lexer.  Handles JUST the shape emitted by
 * poetry.lock / uv.lock:
 *   [table]                        → tables
 *   [[array-of-tables]]            → arraysOfTables
 *   key = "value"                  → scalar strings
 *   key = 1                        → scalar numbers (kept as raw strings)
 *   key = true                     → scalar booleans (kept as raw strings)
 *   key = ["a", "b"]               → arrays of scalars
 *   key = [{a = "b"}, {c = "d"}]   → arrays of inline tables
 *   key = { a = "b", c = "d" }     → inline tables
 *   """triple-quoted"""            → multi-line strings
 *
 * NOT handled (and this is deliberate — a real TOML parser would be a
 * heavyweight dep):
 *   - Datetime literals
 *   - Dotted keys within a table declaration `[package.dependencies]` when
 *     used as a sub-table WITH parent entries above it in the file
 *
 * The dotted-key form IS handled for TABLE HEADERS — `[package.dependencies]`
 * declares a table living UNDER a top-level table `package`, distinct from
 * `[[package]]` array-of-tables. Poetry's real files use both.
 */
interface SimpleTomlDoc {
  rootScalars: Map<string, unknown>;
  tables: Map<string, Map<string, unknown>>;
  arraysOfTables: Map<string, Array<Map<string, unknown>>>;
}

export function parseSimpleToml(text: string): SimpleTomlDoc {
  const doc: SimpleTomlDoc = {
    rootScalars: new Map(),
    tables: new Map(),
    arraysOfTables: new Map(),
  };

  // Current insertion target — starts at root.  When we see [xxx] we switch
  // to a named table.  When we see [[xxx]] we push a fresh table onto the
  // named array and switch to it.
  let current: Map<string, unknown> = doc.rootScalars;

  // Pre-process multi-line strings by collapsing them onto one line surrounded
  // by delimiters that the line-based parser can recognise.  We use `\x00`
  // for line joins inside a preserved multi-line value.
  const preprocessed = preprocessMultilineStrings(text);

  // Collapse multi-line array values (`key = [ \n ... \n ]`) and multi-line
  // inline tables (`key = { \n ... \n }`) onto one logical line by counting
  // bracket depth.  Without this, values that poetry / uv routinely emit as
  // pretty-printed multi-line arrays would parse as an opening `[` with no
  // matching close.
  const collapsed = collapseMultilineValues(preprocessed);

  for (const rawLine of collapsed.split('\n')) {
    let line = rawLine;
    // Strip comment (# NOT preceded by an unescaped quote / backtick)
    line = stripToplevelComment(line).trim();
    if (!line) continue;

    // Section headers
    if (line.startsWith('[[') && line.endsWith(']]')) {
      const path = line.slice(2, -2).trim();
      const parts = path.split('.');
      // Dotted array-of-tables header: `[[package.wheels]]` — attach a new
      // table to the sub-array 'wheels' inside the MOST-RECENT [[package]] entry.
      // This is the shape poetry uses for [[package.files]] and uv uses for
      // [[package.wheels]] / [[package.sdist]].  Without this dispatch,
      // dotted-array headers silently create top-level array-of-tables
      // entries with names like 'package.wheels', and downstream lookups miss
      // the hashes entirely.
      if (parts.length > 1) {
        const head = parts[0]!;
        const rest = parts.slice(1).join('.');
        const parentArr = doc.arraysOfTables.get(head);
        if (parentArr && parentArr.length > 0) {
          const parent = parentArr[parentArr.length - 1]!;
          let sub = parent.get(rest);
          if (!Array.isArray(sub)) {
            sub = [];
            parent.set(rest, sub);
          }
          const fresh = new Map<string, unknown>();
          (sub as unknown[]).push(fresh);
          current = fresh;
          continue;
        }
      }
      const arr = doc.arraysOfTables.get(path) ?? [];
      const fresh = new Map<string, unknown>();
      arr.push(fresh);
      doc.arraysOfTables.set(path, arr);
      current = fresh;
      continue;
    }
    if (line.startsWith('[') && line.endsWith(']')) {
      const path = line.slice(1, -1).trim();
      // If the path is dotted AND the head matches the most recent
      // array-of-tables entry (e.g. [package.dependencies] following a
      // [[package]] block), install the sub-table inside that entry.
      const parts = path.split('.');
      if (parts.length > 1) {
        const head = parts[0]!;
        const rest = parts.slice(1).join('.');
        // Prefer the most recent [[head]] entry over a flat [head] table.
        const arr = doc.arraysOfTables.get(head);
        if (arr && arr.length > 0) {
          const parent = arr[arr.length - 1]!;
          const sub = new Map<string, unknown>();
          parent.set(rest, sub);
          current = sub;
          continue;
        }
      }
      const tbl = doc.tables.get(path) ?? new Map<string, unknown>();
      doc.tables.set(path, tbl);
      current = tbl;
      continue;
    }

    // key = value
    const eq = findKeyValueSplit(line);
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const rawValue = line.slice(eq + 1).trim();
    if (!key) continue;
    const parsedValue = parseTomlValue(rawValue);
    current.set(stripQuotes(key), parsedValue);
  }

  return doc;
}

/**
 * Collapse multi-line array and inline-table values onto one line.  This lets
 * the line-based dispatcher in parseSimpleToml see a full `key = [ ... ]`
 * regardless of pretty-printing.  Preserves line count by inserting empty
 * lines where original newlines were consumed, so error messages that
 * reference line numbers stay approximately accurate.
 */
function collapseMultilineValues(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!;
    // Check whether this line contains an `=` where the RHS starts an
    // unclosed [ or { that spans subsequent lines.
    const eq = findKeyValueSplit(line);
    if (eq === -1) { out.push(line); i++; continue; }
    const rhs = line.slice(eq + 1).trim();
    const opener = rhs[0];
    if (opener !== '[' && opener !== '{') { out.push(line); i++; continue; }
    // Count open/close brackets on this line (respecting quotes)
    const balance = bracketBalance(rhs);
    if (balance === 0) { out.push(line); i++; continue; }
    // Multi-line — accumulate until balanced.
    let joined = line;
    let depth = balance;
    let consumed = 0;
    let j = i + 1;
    while (j < lines.length && depth > 0) {
      const next = lines[j]!;
      joined += ' ' + next.trim();
      depth += bracketBalance(next);
      consumed++;
      j++;
    }
    out.push(joined);
    // Emit blank lines to preserve line numbering.
    for (let k = 0; k < consumed; k++) out.push('');
    i = j;
  }
  return out.join('\n');
}

/** +1 for every unquoted `[` or `{`, -1 for every unquoted `]` or `}`. */
function bracketBalance(s: string): number {
  let n = 0;
  let inString: string | null = null;
  for (let i = 0; i < s.length; i++) {
    const c = s[i]!;
    if (inString) {
      if (c === '\\') { i++; continue; }
      if (c === inString) inString = null;
      continue;
    }
    if (c === '"' || c === "'") { inString = c; continue; }
    if (c === '#') break;
    if (c === '[' || c === '{') n++;
    if (c === ']' || c === '}') n--;
  }
  return n;
}

function preprocessMultilineStrings(text: string): string {
  // Collapse `"""..."""` runs (may span multiple lines) into a single line by
  // replacing newlines inside them with `\x00`, which parseTomlValue will
  // restore. We do the same for `'''...'''`.  This lets the line-based parser
  // handle everything.
  let out = '';
  let i = 0;
  while (i < text.length) {
    // Detect triple-quoted string starts
    if (text.startsWith('"""', i) || text.startsWith("'''", i)) {
      const quote = text.slice(i, i + 3);
      const endIdx = text.indexOf(quote, i + 3);
      if (endIdx === -1) {
        // Unterminated — keep the rest as-is
        out += text.slice(i);
        break;
      }
      const body = text.slice(i, endIdx + 3).replace(/\r?\n/g, '\x00');
      out += body;
      i = endIdx + 3;
      continue;
    }
    out += text[i]!;
    i++;
  }
  return out;
}

/** Find the top-level `=` (not inside a bracket or quote). Return -1 when absent. */
function findKeyValueSplit(line: string): number {
  let inString: string | null = null;
  let depth = 0;
  for (let i = 0; i < line.length; i++) {
    const c = line[i]!;
    if (inString) {
      if (c === '\\') { i++; continue; }
      if (c === inString) inString = null;
      continue;
    }
    if (c === '"' || c === "'") { inString = c; continue; }
    if (c === '[' || c === '{') depth++;
    if (c === ']' || c === '}') depth--;
    if (c === '=' && depth === 0) return i;
  }
  return -1;
}

function stripToplevelComment(line: string): string {
  let inString: string | null = null;
  for (let i = 0; i < line.length; i++) {
    const c = line[i]!;
    if (inString) {
      if (c === '\\') { i++; continue; }
      if (c === inString) inString = null;
      continue;
    }
    if (c === '"' || c === "'") { inString = c; continue; }
    if (c === '#') return line.slice(0, i);
  }
  return line;
}

function stripQuotes(s: string): string {
  const t = s.trim();
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) {
    return t.slice(1, -1);
  }
  return t;
}

/**
 * Parse a TOML value RHS.  Handles strings, numbers, booleans, arrays, and
 * inline tables.  Arrays of inline tables also work.
 */
function parseTomlValue(raw: string): unknown {
  const s = raw.trim();
  if (!s) return '';
  // Triple-quoted (preprocessed with \x00 → \n)
  if ((s.startsWith('"""') && s.endsWith('"""')) || (s.startsWith("'''") && s.endsWith("'''"))) {
    return s.slice(3, -3).replace(/\x00/g, '\n');
  }
  // Single-line strings
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return unescapeTomlString(s.slice(1, -1));
  }
  // Boolean
  if (s === 'true') return true;
  if (s === 'false') return false;
  // Array
  if (s.startsWith('[') && s.endsWith(']')) {
    return parseTomlArray(s.slice(1, -1));
  }
  // Inline table
  if (s.startsWith('{') && s.endsWith('}')) {
    return parseTomlInlineTable(s.slice(1, -1));
  }
  // Number (kept as string — we don't need typed numeric values downstream)
  if (/^-?\d/.test(s)) return s;
  // Bare identifier — keep the string as-is
  return s;
}

function unescapeTomlString(s: string): string {
  // Only handle the minimal escapes poetry/uv emit.
  return s
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, '\r')
    .replace(/\\t/g, '\t')
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
}

function parseTomlArray(body: string): unknown[] {
  const items: unknown[] = [];
  for (const chunk of splitTopLevel(body, ',')) {
    const t = chunk.trim();
    if (!t) continue;
    items.push(parseTomlValue(t));
  }
  return items;
}

function parseTomlInlineTable(body: string): Map<string, unknown> {
  const out = new Map<string, unknown>();
  for (const chunk of splitTopLevel(body, ',')) {
    const eq = findKeyValueSplit(chunk);
    if (eq === -1) continue;
    const key = stripQuotes(chunk.slice(0, eq).trim());
    const val = parseTomlValue(chunk.slice(eq + 1).trim());
    if (key) out.set(key, val);
  }
  return out;
}

/** Split a string on `sep` respecting brackets/quotes. */
function splitTopLevel(s: string, sep: string): string[] {
  const out: string[] = [];
  let buf = '';
  let inString: string | null = null;
  let depth = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s[i]!;
    if (inString) {
      buf += c;
      if (c === '\\') { if (i + 1 < s.length) { buf += s[i + 1]; i++; } continue; }
      if (c === inString) inString = null;
      continue;
    }
    if (c === '"' || c === "'") { inString = c; buf += c; continue; }
    if (c === '[' || c === '{') { depth++; buf += c; continue; }
    if (c === ']' || c === '}') { depth--; buf += c; continue; }
    if (c === sep && depth === 0) {
      out.push(buf);
      buf = '';
      continue;
    }
    buf += c;
  }
  if (buf) out.push(buf);
  return out;
}
