/**
 * Universal lockfile dispatcher — auto-detect the format from filename and/or
 * content, then delegate to the right parser.
 *
 * Supported:
 *   - package-lock.json    (npm v2+, existing parser)
 *   - pnpm-lock.yaml       (pnpm v5+, js-yaml-backed parser)
 *   - yarn.lock            (yarn classic v1 + yarn berry v2+)
 *   - requirements.txt     (pip freeze — P4c PyPI adapter)
 *   - poetry.lock          (poetry v1/v2/v3 — P4c PyPI adapter)
 *   - uv.lock              (uv v1 — P4c PyPI adapter)
 *
 * Returns a `LockGraph` regardless of source format.
 *
 * P4c: PyPI kinds are attempted after the npm-family kinds. `parseLockfileText`
 * returns a discriminated `.kind` so the engine layer can pick the right
 * ecosystem adapter downstream (npm-family → pacote fetch; pypi-* → PyPI JSON
 * API fetch).
 */

import type { LockGraph } from './lockfile.js';
import { parseLockfile as parseNpmLock, UnsupportedLockfileError } from './lockfile.js';
import { parsePnpmLockText } from './lockfile-pnpm.js';
import { parseYarnLockText } from './lockfile-yarn.js';
import {
  parsePypiLockfileText,
  type PypiLockfileKind,
} from './lockfile-pypi.js';

export type NpmFamilyKind = 'npm' | 'pnpm' | 'yarn-classic' | 'yarn-berry';
export type LockfileKind = NpmFamilyKind | PypiLockfileKind;

export type Ecosystem = 'npm' | 'pypi';

export interface DetectionResult {
  kind: LockfileKind;
  ecosystem: Ecosystem;
  graph: LockGraph;
}

/**
 * Parse lockfile text — kind is detected from `filename` when provided, or by
 * peeking at the first few bytes of `text`.
 *
 * P4c: PyPI lockfiles (requirements.txt / poetry.lock / uv.lock) are detected
 * first when the filename hint identifies them; otherwise the pre-existing
 * npm-family detection runs, and PyPI content-sniff is only tried when the
 * npm-family sniff throws.
 */
export function parseLockfileText(text: string, filename?: string): DetectionResult {
  const kind = detectKind(text, filename);
  switch (kind) {
    case 'npm': {
      const graph = parseNpmLock(JSON.parse(text));
      return { kind, ecosystem: 'npm', graph };
    }
    case 'pnpm': {
      const graph = parsePnpmLockText(text);
      return { kind, ecosystem: 'npm', graph };
    }
    case 'yarn-classic':
    case 'yarn-berry': {
      const graph = parseYarnLockText(text);
      return { kind, ecosystem: 'npm', graph };
    }
    case 'pypi-requirements':
    case 'pypi-poetry':
    case 'pypi-uv': {
      const result = parsePypiLockfileText(text, filename);
      return { kind, ecosystem: 'pypi', graph: result.graph };
    }
    default:
      throw new UnsupportedLockfileError(`unable to detect lockfile format`);
  }
}

export function detectKind(text: string, filename?: string): LockfileKind {
  if (filename) {
    const base = filename.split(/[\\/]/).pop() ?? '';
    if (base === 'package-lock.json' || base === 'npm-shrinkwrap.json') return 'npm';
    if (base === 'pnpm-lock.yaml' || base === 'pnpm-lock.yml') return 'pnpm';
    if (base === 'yarn.lock') {
      // Could be classic or berry — peek at content
      return /^\s*__metadata:/m.test(text) ? 'yarn-berry' : 'yarn-classic';
    }
    if (base === 'requirements.txt' || /^requirements[-.\w]*\.txt$/.test(base)) {
      return 'pypi-requirements';
    }
    if (base === 'poetry.lock') return 'pypi-poetry';
    if (base === 'uv.lock') return 'pypi-uv';
  }
  // Content-only detection — npm family first (JSON / pnpm YAML / yarn), then PyPI
  const trimmed = text.trimStart();
  if (trimmed.startsWith('{')) return 'npm';
  if (/^lockfileVersion:/m.test(trimmed)) return 'pnpm';
  if (/^__metadata:/m.test(trimmed)) return 'yarn-berry';
  if (/^# yarn lockfile v1/m.test(trimmed) || /^\w[\w./@-]*@[^:]+:\s*$/m.test(trimmed)) return 'yarn-classic';
  // PyPI content sniffs
  if (/# This file (?:was )?autogenerated by uv/i.test(text)) return 'pypi-uv';
  if (/^\[metadata\][\s\S]*lock-version\s*=/m.test(text)) return 'pypi-poetry';
  if (/^\[\[package\]\]/m.test(text) && /^\s*version\s*=\s*\d/m.test(text)) return 'pypi-uv';
  if (/^[A-Za-z0-9_.-]+\s*==\s*[\w.+-]+/m.test(text)) return 'pypi-requirements';
  throw new UnsupportedLockfileError('could not detect lockfile format from content');
}
