/**
 * P1-A · CLI no-crash regression for pnpm-lock.yaml and yarn.lock.
 *
 * A defense-in-depth test that runs the built CLI as a subprocess against
 * pnpm and yarn lockfiles. Even if unit-level parsing works, the CLI can
 * regress if a code path in cli.ts crashes on YAML input (e.g. a downstream
 * consumer that assumes JSON). This test asserts exit code != 3 (the
 * historical "unhandled crash" exit — vetlock reserves 0/1/2 for CLEAN/WARN/
 * BLOCK, 3 for analyzer bombed).
 *
 * We DON'T assert on network-dependent verdicts here: the CLI will try to
 * fetch the real tarballs from npm and will either succeed (verdict depends
 * on the diff) or fall back to `analysis.failed` BLOCK (S10 fail-closed).
 * Both are non-crash outcomes; either is acceptable for THIS test.
 */

import { describe, it, expect } from 'vitest';
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..', '..');
const CLI = path.join(REPO_ROOT, 'packages', 'cli', 'dist', 'cli.js');

function withTempDir<T>(fn: (dir: string) => T): T {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'vetlock-cli-nocrash-'));
  try { return fn(dir); } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

function runCli(args: string[]): { code: number | null; stdout: string; stderr: string } {
  // Explicitly no-progress + JSON so the CLI doesn't try to render a spinner
  // (which fails in a non-TTY test env with certain terminal detection paths).
  const res = spawnSync('node', [CLI, ...args, '--json', '--no-progress'], {
    encoding: 'utf8',
    timeout: 60_000,
  });
  return { code: res.status, stdout: res.stdout ?? '', stderr: res.stderr ?? '' };
}

describe('CLI no-crash on pnpm-lock.yaml and yarn.lock (P1-A regression guard)', () => {
  it('exits 0/1/2 (never 3) on a real-shape pnpm-lock.yaml pair', () => {
    withTempDir((dir) => {
      const before = path.join(dir, 'pnpm-lock.yaml');
      const after = path.join(dir, 'pnpm-lock.after.yaml');
      // Trivial pnpm-lock.yaml v9 pair — same package, bumped version.
      fs.writeFileSync(before, `lockfileVersion: '9.0'\nimporters:\n  .:\n    dependencies:\n      no-op:\n        specifier: ^1.0.0\n        version: 1.0.0\npackages:\n  no-op@1.0.0:\n    resolution: {integrity: sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==}\n`);
      fs.writeFileSync(after, `lockfileVersion: '9.0'\nimporters:\n  .:\n    dependencies:\n      no-op:\n        specifier: ^1.0.0\n        version: 1.0.1\npackages:\n  no-op@1.0.1:\n    resolution: {integrity: sha512-BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB==}\n`);

      const result = runCli(['diff', before, after]);
      // Exit code semantics: 0 = clean, 1 = warn, 2 = block/fail-on, 3 = analyzer bombed, others = wrapper crash.
      // We accept 0/1/2 (real verdicts) but NOT 3 (unhandled crash — the F1 signature).
      expect([0, 1, 2]).toContain(result.code);
      // Guard against SyntaxError-from-JSON.parse leaking into stderr.
      expect(result.stderr).not.toMatch(/SyntaxError.*JSON/);
      expect(result.stderr).not.toMatch(/Unexpected token/);
    });
  });

  it('exits 0/1/2 (never 3) on a yarn classic v1 lockfile pair', () => {
    withTempDir((dir) => {
      const before = path.join(dir, 'yarn.lock');
      const after = path.join(dir, 'yarn.after.lock');
      fs.writeFileSync(before, `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\nno-op@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/no-op/-/no-op-1.0.0.tgz#dead"\n  integrity sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\n`);
      fs.writeFileSync(after, `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\nno-op@^1.0.0:\n  version "1.0.1"\n  resolved "https://registry.yarnpkg.com/no-op/-/no-op-1.0.1.tgz#beef"\n  integrity sha512-BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB==\n`);

      const result = runCli(['diff', before, after]);
      expect([0, 1, 2]).toContain(result.code);
      expect(result.stderr).not.toMatch(/SyntaxError.*JSON/);
      expect(result.stderr).not.toMatch(/Unexpected token/);
    });
  });
});
