/**
 * Report generator (ADR-0004 metrics § of PACKET-VETLOCK-ASSURANCE §4).
 *
 * Produces `assurance/report/ASSURANCE.md` — the public trust artifact every vetlock release
 * links to. The report contains only what's been actually measured; when a tier is not yet
 * active it says "no data" rather than fabricating a green metric.
 *
 * Reproducibility is a hard invariant: two calls to `generateReport(input)` with the same
 * input must produce byte-identical output. This means:
 *   - No `Date.now()` or `new Date()` inside — timestamps come from `input.stamp.timestampIso`.
 *   - No `Math.random()` — nothing here draws randomness.
 *   - No non-deterministic iteration order — every list is sorted before rendering.
 * The report generator has a self-test that runs it twice and asserts byte-equal output.
 */

/** Everything the report needs, provided by the caller. Kept as a plain value so it's easy
 *  to snapshot, replay, or feed from CI. */
export interface ReportInput {
  readonly stamp: {
    /** Timestamp in ISO 8601 UTC, e.g. "2026-07-14T12:00:00Z". Caller supplies. */
    readonly timestampIso: string;
    /** git commit SHA of the vetlock repo at generation time. Full 40-char SHA or 'unknown'. */
    readonly gitSha: string;
    /** Node version, e.g. "v20.11.0". */
    readonly nodeVersion: string;
    /** Seed used for any RNG in the run tier (echoed here so failures replay). */
    readonly seed: number;
    /** Which tier produced the numbers below: 'pr' (blocking, fast) or 'scheduled' (nightly).
     *  P0's foundations tier is neither — it uses 'foundations' as a self-declaration. */
    readonly tier: 'foundations' | 'pr' | 'scheduled';
  };
  /**
   * Metrics (packet §4). Any metric can be `null`, meaning "no data yet" — the report
   * distinguishes null from 0 in text.
   *   robustnessPassRate      — 0..1 (100% required at PR-tier gate).
   *   enumeratedCoverage      — 0..1 across the CAPABILITY-MAP.
   *   evasionCatchRate        — 0..1.
   *   metamorphicInvariance   — 0..1.
   *   differentialLedgerNote  — free-text: how many deltas, all classified?
   */
  readonly metrics: {
    readonly robustnessPassRate: number | null;
    readonly enumeratedCoverage: number | null;
    readonly evasionCatchRate: number | null;
    readonly metamorphicInvariance: number | null;
    readonly differentialLedgerNote: string | null;
  };
  /** Named notes to render under "Gaps & follow-ups", sorted before rendering. */
  readonly notes?: readonly { readonly title: string; readonly body: string }[];
}

// ---------------------------------------------------------------------------------------------

/** Format a rate 0..1 as "NN.N%", or the placeholder for null. */
function formatRate(value: number | null): string {
  if (value === null) return 'no data (tier not yet active)';
  const pct = value * 100;
  return `${pct.toFixed(1)}%`;
}

function formatMetric(label: string, value: number | null, gate: string): string {
  return `- **${label}:** ${formatRate(value)} · gate: ${gate}`;
}

/** Sort notes deterministically by title. */
function sortNotes(
  notes: ReadonlyArray<{ readonly title: string; readonly body: string }>,
): ReadonlyArray<{ readonly title: string; readonly body: string }> {
  return [...notes].sort((a, b) => (a.title < b.title ? -1 : a.title > b.title ? 1 : 0));
}

/**
 * Produce the ASSURANCE.md content. Pure function — no I/O, no clock reads.
 */
export function generateReport(input: ReportInput): string {
  const { stamp, metrics, notes } = input;
  const lines: string[] = [];

  lines.push('# ASSURANCE.md');
  lines.push('');
  lines.push(
    'The standing-adversary scorecard for the vetlock engine. Regenerated by ' +
      '`pnpm --filter @vetlock/assurance assurance:report`. Every number below is reproducible ' +
      'from the seed and git SHA in the stamp.',
  );
  lines.push('');
  lines.push('## Stamp');
  lines.push('');
  lines.push(`- **Generated:** ${stamp.timestampIso}`);
  lines.push(`- **Tier:** ${stamp.tier}`);
  lines.push(`- **Git SHA:** \`${stamp.gitSha}\``);
  lines.push(`- **Node version:** ${stamp.nodeVersion}`);
  lines.push(`- **Seed:** ${stamp.seed}`);
  lines.push('');
  lines.push('## Metrics');
  lines.push('');
  lines.push(
    formatMetric('Robustness pass-rate', metrics.robustnessPassRate, '100% at PR tier'),
  );
  lines.push(
    formatMetric(
      'Enumerated CAPABILITY-MAP coverage',
      metrics.enumeratedCoverage,
      '100% of enumerated sinks + entry-points',
    ),
  );
  lines.push(
    formatMetric('Evasion catch-rate', metrics.evasionCatchRate, '100% at PR tier'),
  );
  lines.push(
    formatMetric(
      'Metamorphic invariance',
      metrics.metamorphicInvariance,
      '100% of identity-invariant pairs',
    ),
  );
  lines.push(
    `- **Differential deltas:** ${metrics.differentialLedgerNote ?? 'no data (tier not yet active)'} · gate: classified ledger, no silent hits`,
  );
  lines.push('');
  lines.push('## Honesty note');
  lines.push('');
  lines.push(
    '`100% of enumerated sinks` is a floor, not a ceiling. The CAPABILITY-MAP (STARTUP §3.5) ' +
      'is the definition of what the harness enumerates; the adversarial-agent panel ' +
      '(ADR 0002 modality 4) exists to keep growing that enumeration. This report never claims ' +
      'completeness beyond the enumerated set.',
  );

  const sortedNotes = notes && notes.length > 0 ? sortNotes(notes) : [];
  if (sortedNotes.length > 0) {
    lines.push('');
    lines.push('## Gaps & follow-ups');
    lines.push('');
    for (const note of sortedNotes) {
      lines.push(`### ${note.title}`);
      lines.push('');
      lines.push(note.body);
      lines.push('');
    }
    // Trailing blank line is elided by the final newline below.
    while (lines.length > 0 && lines[lines.length - 1] === '') {
      lines.pop();
    }
  }

  // A single trailing newline. Deterministic file endings matter for byte-equality tests.
  return lines.join('\n') + '\n';
}
