/**
 * Markdown renderer — designed for pasting as a PR comment body.
 */

import type { Finding, RunResult, Severity } from '@vetlock/core';

const EMOJI: Record<Severity | 'CLEAN', string> = {
  BLOCK: '🚫',
  WARN: '⚠️',
  INFO: 'ℹ️',
  CLEAN: '✅',
};

export function renderMarkdown(result: RunResult): string {
  const lines: string[] = [];
  lines.push(`### ${EMOJI[result.verdict]} vetlock — behavioral diff`);
  lines.push('');
  lines.push(
    `**${result.verdict}** · ${result.findings.length} finding${
      result.findings.length === 1 ? '' : 's'
    } across ${result.changes.length} changed package${result.changes.length === 1 ? '' : 's'}.`,
  );
  lines.push('');

  if (result.findings.length === 0) {
    lines.push('_No behavioral changes detected in this update._');
    return lines.join('\n');
  }

  // Group by severity
  const groups: Record<Severity, Finding[]> = { BLOCK: [], WARN: [], INFO: [] };
  for (const f of result.findings) groups[f.severity].push(f);

  for (const sev of ['BLOCK', 'WARN', 'INFO'] as const) {
    const fs = groups[sev];
    if (fs.length === 0) continue;
    lines.push(`#### ${EMOJI[sev]} ${sev} (${fs.length})`);
    lines.push('');
    // Sub-group by package
    const byPkg = new Map<string, Finding[]>();
    for (const f of fs) {
      (byPkg.get(f.package) ?? byPkg.set(f.package, []).get(f.package)!).push(f);
    }
    for (const [pkg, findings] of byPkg) {
      const first = findings[0]!;
      const version = first.from && first.to ? `${first.from} → ${first.to}` : first.to ?? first.from;
      lines.push(`- **\`${pkg}\`** \`${version}\``);
      if (first.provenance.length > 0) {
        lines.push(`  - via: \`${first.provenance[0]!.join(' → ')}\``);
      }
      for (const f of findings) {
        lines.push(`  - **\`${f.detector}\`** — ${f.message}`);
        for (const ev of f.evidence.slice(0, 2)) {
          lines.push(`    - \`${ev.file}:${ev.line}\` — \`${escape(ev.snippet)}\``);
        }
      }
    }
    lines.push('');
  }

  lines.push(`_generated by vetlock in ${result.durationMs}ms_`);
  return lines.join('\n');
}

function escape(s: string): string {
  return s.replace(/`/g, '\\`').slice(0, 200);
}
