/**
 * metamorphic-invariance.test — the P3 end-to-end oracle probe (packet §5 P3).
 *
 * For every pair `(a, b)` generated by `generatePairBattery(seed, count)`:
 *   1. Analyze `a` via the engine's per-file capability entrypoint through the bounded
 *      runner's `engine:extractCapabilities` scenario (see
 *      assurance/src/runner/types.ts + assurance/src/runner/worker.ts). The worker
 *      dynamically imports `@vetlock/core`, calls `extractCapabilities`, and returns
 *      the FileCapabilities adapted to the assurance Findings shape.
 *   2. Analyze `b` via the same entrypoint. Both A and B use the SAME `relPath` — the
 *      oracle keys on `location.file`, so any per-invocation path variation would
 *      trivially break invariance for reasons unrelated to the analyzer's decision
 *      surface.
 *   3. Feed both outcomes through `oracleIdentityInvariant`, which normalizes
 *      (sort by file/line/column/class/severity/reason/meta) and asserts equality.
 *   4. If the oracle fails, that IS a real completeness finding — the analyzer's
 *      decision surface is inconsistent for a metamorphic transformation. Per the
 *      KNOWN GAPS PROTOCOL (see robustness/no-crash.test.ts), the failing pair is
 *      captured as a corpus entry under assurance/corpus/metamorphic/<pair-id>/
 *      and the test pins the current behavior.
 *
 * WIRING (closed in Wave 3-O + Wave 4-Q):
 * ---------------------------------------
 * The bounded runner now exposes `engine:extractCapabilities` — the assurance-side
 * scenario that hands JS source to the engine's per-file capability scanner. This
 * removes the last blocker to the metamorphic e2e: source pairs flow through the
 * worker, the FileCapabilities → Findings adapter, and the identity oracle without
 * touching the network, filesystem, or any live payload.
 *
 * CLOSED GAP (assurance Wave 5-W, 2026-07-14):
 * --------------------------------------------
 * The battery originally surfaced ONE real completeness gap on 2026-07-14:
 *
 *   • equivalent-expression-string-concat-vs-template — the analyzer emitted an
 *     extra intermediate URL literal for the string-concatenation form. Fixed in
 *     Wave 5-W by having the post-fold sweep skip any folded node whose parent is
 *     also folded (the parent's folded value is a strict superset). The dedicated
 *     GAP-pinning assertion below has been FLIPPED to `expect(pass).toBe(true)` —
 *     it now proves the fix instead of pinning the failing behavior. See
 *     assurance/corpus/metamorphic/equivalent-expression-string-concat-vs-template/README.md
 *     for the full write-up (marked CLOSED).
 *
 * The pair is intentionally still routed through a dedicated test (not folded back
 * into `cleanPairs`) so a future regression would show up as a targeted failure
 * with the corpus reference right there in the assertion — not just as one of 20
 * anonymous per-pair failures.
 */

import { describe, it, expect } from 'vitest';
import { runBounded } from '../../src/runner/index.js';
import type { Bounds, RunOutcome } from '../../src/oracles/types.js';
import { oracleIdentityInvariant } from '../../src/oracles/identity-invariant.js';
import {
  generatePairBattery,
  allPairGenerators,
  type MetamorphicPair,
} from '../../src/metamorphic/index.js';

/** Shared bounds — extractCapabilities is a pure AST scan; 5s + 128 MB is generous. */
const BOUNDS: Bounds = { wallMs: 5_000, heapMb: 128, seed: 42 };

/**
 * Synthetic path handed to the engine. Both A and B in every pair use this same path so
 * `location.file` normalization is a wash — the oracle's decision then reflects the
 * capability set the scanner extracted, not a spurious path difference.
 */
const PAIR_REL_PATH = 'pair.js';

/**
 * Pair ids that at some point violated the metamorphic invariant and are now
 * routed to a dedicated fix-holds test below (in ADDITION to the generic
 * cleanPairs loop). Kept empty for now: the only recorded gap
 * (equivalent-expression-string-concat-vs-template) was closed in assurance
 * Wave 5-W, so the pair rejoins cleanPairs but retains a targeted assertion
 * further down that gives it a named regression home with the corpus
 * reference in the diagnostic.
 *
 * When a NEW pair fails the generic loop, add its id here to exclude it from
 * cleanPairs, then add a targeted GAP-pinning test that flips to `pass=true`
 * once STARTUP closes the fix.
 */
const KNOWN_GAP_IDS: ReadonlySet<string> = new Set([]);

/**
 * Feed one source string through the bounded runner's engine:extractCapabilities
 * scenario. Returns whatever RunOutcome the runner produced — never throws. Failures
 * that break the oracle (crash/timeout/oom) surface in the identity-invariant verdict.
 */
async function analyzeSource(source: string): Promise<RunOutcome> {
  return runBounded(
    {
      kind: 'engine:extractCapabilities',
      enginePath: '@vetlock/core',
      relPath: PAIR_REL_PATH,
      text: source,
    },
    BOUNDS,
  );
}

describe('metamorphic-invariance (packet §5 P3)', () => {
  // Battery driven by a fixed seed so the report and any regression are reproducible.
  const battery: readonly MetamorphicPair[] = generatePairBattery(2026, 20);
  const cleanPairs = battery.filter((p) => !KNOWN_GAP_IDS.has(p.id));

  it('battery is non-empty and cycles across every registered family', () => {
    // Sanity: the battery exists, has the expected shape, and every family is
    // represented at least once when count >= |families|.
    expect(battery.length).toBe(20);
    const families = new Set(battery.map((p) => p.family));
    for (const gen of allPairGenerators) {
      expect(families.has(gen.family)).toBe(true);
    }
  });

  it.each(cleanPairs)(
    'oracleIdentityInvariant passes for pair $id ($family)',
    async (pair) => {
      const outcomeA = await analyzeSource(pair.a);
      const outcomeB = await analyzeSource(pair.b);
      const result = oracleIdentityInvariant(outcomeA, outcomeB);
      if (!result.pass) {
        throw new Error(
          `metamorphic invariance violated on pair ${pair.id} (${pair.family}):\n` +
            `  reason: ${result.reason}\n` +
            `  evidence: ${JSON.stringify(result.evidence)}\n` +
            `  A:\n${pair.a}\n  B:\n${pair.b}`,
        );
      }
      expect(result.pass).toBe(true);
    },
    // Each pair runs A+B through the worker — allow enough wall to cover both spawns
    // plus the runner's own bookkeeping. Extract itself is milliseconds.
    30_000,
  );

  it(
    'oracleIdentityInvariant passes for the non-gap portion of the battery (aggregate spot-check)',
    async () => {
      // Structural sanity — every non-gap pair must pass. This second assertion is
      // intentional redundancy: a single failure in the per-pair test above blows the
      // report open, and this aggregate check ensures the harness itself is exercising
      // every entry (guards against future refactors silently skipping pairs).
      let passes = 0;
      const failures: { id: string; reason: string }[] = [];
      for (const pair of cleanPairs) {
        const oa = await analyzeSource(pair.a);
        const ob = await analyzeSource(pair.b);
        const r = oracleIdentityInvariant(oa, ob);
        if (r.pass) {
          passes++;
        } else {
          failures.push({ id: pair.id, reason: r.reason ?? 'unknown' });
        }
      }
      if (failures.length > 0) {
        throw new Error(
          `aggregate invariance check: ${failures.length}/${cleanPairs.length} pairs failed:\n` +
            failures.map((f) => `  ${f.id}: ${f.reason}`).join('\n'),
        );
      }
      expect(passes).toBe(cleanPairs.length);
    },
    // 20 pairs × 2 analyses × <1s each in practice; cap generously to survive
    // vitest fork concurrency + a cold worker spawn.
    120_000,
  );

  // ------------------------------------------------------------------------------------------
  // CLOSED GAPS (packet rule #6) — each pair below at some point violated the metamorphic
  // invariant, was captured as a corpus entry, and has since been fixed in the engine. The
  // dedicated test remains so a future regression would surface as a targeted failure with
  // the corpus reference immediately visible in the diagnostic (rather than as one of 20
  // anonymous per-pair failures in the generic cleanPairs loop).
  // ------------------------------------------------------------------------------------------

  it(
    'CLOSED (Wave 5-W): equivalent-expression-string-concat-vs-template — engine no longer emits intermediate URL literal',
    async () => {
      // Was: the analyzer's constant-folding pass over "http://" + host + "/api" emitted an
      // intermediate value ("http://example.com") as its own URL literal before folding in
      // "/api". The template-literal form folded in one pass and skipped the intermediate.
      // Both programs are runtime-equivalent — same imports, same call, same argument.
      //
      // Fix (Wave 5-W, packages/core/src/capabilities.ts iterateFolds): the post-fold
      // sweep now skips any folded node whose parent is also folded — the parent's folded
      // value is a strict superset, so all URL / path / encoded-URL signal is preserved
      // and the metamorphic-shape asymmetry is eliminated.
      //
      // See assurance/corpus/metamorphic/equivalent-expression-string-concat-vs-template/README.md
      // (marked CLOSED with the fix commit SHA).
      const gapPair = battery.find(
        (p) => p.id === 'equivalent-expression-string-concat-vs-template',
      );
      // Guard: if the battery seed/count/order ever changes and this pair no longer
      // appears, we want to know immediately rather than silently skip.
      expect(gapPair, 'expected closed-gap pair to appear in battery(2026, 20)').toBeDefined();
      if (!gapPair) return;

      const outcomeA = await analyzeSource(gapPair.a);
      const outcomeB = await analyzeSource(gapPair.b);
      const result = oracleIdentityInvariant(outcomeA, outcomeB);

      // The fix must hold: the oracle passes, both forms produce identical findings.
      expect(result.pass).toBe(true);

      // Structural sanity: both A and B produced an `ok` outcome (no crash, no fail-safe,
      // no timeout). If this ever regresses to false=findings-differ, the reason string
      // will surface the exact count asymmetry (e.g. "findings count differs (3 vs 2)"),
      // pointing straight back at capabilities.ts iterateFolds.
      expect(outcomeA.kind).toBe('ok');
      expect(outcomeB.kind).toBe('ok');
    },
    30_000,
  );
});
