/**
 * metamorphic-invariance.test — the P3 end-to-end oracle probe (packet §5 P3).
 *
 * For every pair `(a, b)` generated by `generatePairBattery(seed, count)`:
 *   1. Analyze `a` via the engine's per-file capability entrypoint
 *      (`extractCapabilities(relPath, text, sha256, bytes)` — see
 *      `packages/core/src/capabilities.ts`).
 *   2. Analyze `b` via the same entrypoint.
 *   3. Adapt the engine's `FileCapabilities` into the assurance-side `Findings` shape
 *      and feed BOTH through `oracleIdentityInvariant`.
 *   4. Assert `oracleIdentityInvariant(...).pass === true`.
 *
 * WIRING GAP (documented for P1 to close):
 * ----------------------------------------
 * The bounded runner (assurance/src/runner) currently exposes exactly two engine
 * scenarios: `engine:parseLockfileText` and `engine:runDiff`. Both operate on
 * *lockfile* input (npm/yarn/pnpm), not on raw JS source. Metamorphic pairs are JS
 * source, so there is no direct in-runner path today: we would need a new scenario
 * kind (`engine:extractCapabilities`) that imports `@vetlock/core`, calls
 * `extractCapabilities(relPath, text, sha256, bytes)` in the worker, adapts the
 * per-file capability structure into `Findings`, and returns a `RunOutcome`.
 *
 * Rather than smuggle JS source through `parseLockfileText` (that entrypoint would
 * reject it as an unsupported lockfile format — see `engine-wiring.test.ts` for
 * that behavior), P3 lands the FRAMEWORK now (generators + battery + tests) and
 * pins the e2e assertion as `it.skip(...)` with the exact wiring the follow-on
 * phase needs to un-skip. Unskipping is a two-step patch:
 *
 *   1. Add `engine:extractCapabilities` to `Scenario` (assurance/src/runner/types.ts),
 *      handle it in `assurance/src/runner/worker.ts`, and expose it through
 *      `runBounded`. The worker calls `import('@vetlock/core').extractCapabilities`,
 *      converts the per-file capability set into the assurance `Findings` shape via
 *      an adapter analogous to `engine-adapter.ts::adaptFinding`.
 *
 *   2. Remove `.skip` from the test blocks below.
 *
 * Corpus regression path is already prepared: any pair that fails the oracle can be
 * committed to `assurance/corpus/metamorphic/<family>/<id>/` per packet rule #6.
 */

import { describe, it, expect } from 'vitest';
import type { RunOutcome, Findings } from '../../src/oracles/types.js';
import { oracleIdentityInvariant } from '../../src/oracles/identity-invariant.js';
import {
  generatePairBattery,
  allPairGenerators,
  type MetamorphicPair,
} from '../../src/metamorphic/index.js';

/**
 * The intended per-pair check, factored out so unskipping is a one-liner.
 *
 * `analyze` is the placeholder for the future `engine:extractCapabilities` runner
 * scenario. Once that lands, this function becomes a real call site — the test
 * body below already threads `pair.a` and `pair.b` through it.
 */
async function analyzeSourcePlaceholder(_source: string): Promise<RunOutcome> {
  // This function is intentionally unreachable while the e2e is skipped. Types are
  // pinned so the surrounding test code stays valid; the future implementation will
  // call `runBounded({ kind: 'engine:extractCapabilities', enginePath: '@vetlock/core',
  // relPath: 'pair.js', text: source }, BOUNDS)` and return the resulting outcome.
  throw new Error(
    'engine:extractCapabilities scenario not yet wired — see file-level comment for the patch shape.',
  );
}

/** Build a synthetic `ok` outcome with the given findings (used only as a shape reference). */
function synthOk(findings: Findings): RunOutcome {
  return { kind: 'ok', findings, wallMs: 0, peakRssBytes: 0, seed: 0 };
}

describe('metamorphic-invariance (packet §5 P3)', () => {
  // Battery driven by a fixed seed so the report and any regression are reproducible.
  const battery: readonly MetamorphicPair[] = generatePairBattery(2026, 20);

  it('battery is non-empty and cycles across every registered family', () => {
    // This assertion runs to prove the harness scaffolding is real even while the
    // e2e is skipped: the battery exists, has the expected shape, and every family
    // is represented at least once when count >= |families|.
    expect(battery.length).toBe(20);
    const families = new Set(battery.map((p) => p.family));
    for (const gen of allPairGenerators) {
      expect(families.has(gen.family)).toBe(true);
    }
  });

  it.skip.each(battery)(
    'oracleIdentityInvariant passes for pair $id ($family)',
    async (pair) => {
      const outcomeA = await analyzeSourcePlaceholder(pair.a);
      const outcomeB = await analyzeSourcePlaceholder(pair.b);
      const result = oracleIdentityInvariant(outcomeA, outcomeB);
      if (!result.pass) {
        throw new Error(
          `metamorphic invariance violated on pair ${pair.id} (${pair.family}):\n` +
            `  reason: ${result.reason}\n` +
            `  A:\n${pair.a}\n  B:\n${pair.b}`,
        );
      }
      expect(result.pass).toBe(true);
    },
  );

  it.skip(
    'oracleIdentityInvariant passes for the full battery in aggregate (structural spot-check)',
    async () => {
      // Structural sanity — once wired, we expect *every* pair to pass. This second
      // assertion is intentional redundancy: a single failure in the per-pair test
      // above blows the report open, and this aggregate check ensures the harness
      // itself is exercising every entry (guards against `describe.skip` swallowing
      // silently on future refactors).
      let passes = 0;
      for (const pair of battery) {
        const oa = await analyzeSourcePlaceholder(pair.a);
        const ob = await analyzeSourcePlaceholder(pair.b);
        const r = oracleIdentityInvariant(oa, ob);
        if (r.pass) passes++;
      }
      expect(passes).toBe(battery.length);
      // Keep the synth helper referenced so the compiler doesn't strip it — the
      // future patch may repurpose it for a fixture-based sub-test.
      void synthOk([]);
    },
  );
});
