/**
 * @vetlock/assurance metamorphic pair generators (packet §2.2, §5 P3).
 *
 * A metamorphic pair is two source strings that MUST behave identically at runtime.
 * If the analyzer produces different findings on them, the analyzer's decision surface
 * is inconsistent — a completeness gap.
 *
 * Five pair families ship in P3:
 *   • statement-reorder     — swap two independent top-level statements
 *   • alpha-rename          — rename an LHS binding without touching usage
 *   • equivalent-expression — semantically-equivalent expression forms
 *   • whitespace-comments   — inject comments + whitespace into A to make B
 *   • member-access-form    — `obj.foo` vs `obj["foo"]` (dot vs computed)
 *
 * Each generator is pure: same seed → byte-identical pair. The `allPairGenerators`
 * array is the canonical enumeration and drives the invariance test.
 */

export type { MetamorphicPair, PairGenerator } from './types.js';

export { statementReorder } from './statement-reorder.js';
export { alphaRename } from './alpha-rename.js';
export { equivalentExpression } from './equivalent-expression.js';
export { whitespaceComments } from './whitespace-comments.js';
export { memberAccessForm } from './member-access-form.js';

import type { MetamorphicPair, PairGenerator } from './types.js';
import { statementReorder } from './statement-reorder.js';
import { alphaRename } from './alpha-rename.js';
import { equivalentExpression } from './equivalent-expression.js';
import { whitespaceComments } from './whitespace-comments.js';
import { memberAccessForm } from './member-access-form.js';

/**
 * Canonical enumeration of pair generators. Order is stable so that
 * `generatePairBattery(seed, N)` cycles through families in a documented sequence.
 */
export const allPairGenerators: readonly PairGenerator[] = [
  statementReorder,
  alphaRename,
  equivalentExpression,
  whitespaceComments,
  memberAccessForm,
];

/**
 * Produce `count` pairs by cycling through `allPairGenerators`. The i-th pair is
 * generated by family (i mod N) with seed derived from `(seed, i)` — enough to give
 * every pair a distinct, reproducible seed while keeping the whole battery
 * deterministic for a caller-provided root seed.
 *
 * Battery ids are stable per (seed, count, index) so a failing pair replays.
 */
export function generatePairBattery(
  seed: number,
  count: number,
): readonly MetamorphicPair[] {
  if (!Number.isInteger(count) || count < 0) {
    throw new Error(`generatePairBattery: count must be a non-negative integer; got ${count}`);
  }
  if (allPairGenerators.length === 0) {
    throw new Error('generatePairBattery: no generators registered');
  }
  const pairs: MetamorphicPair[] = [];
  for (let i = 0; i < count; i++) {
    const gen = allPairGenerators[i % allPairGenerators.length];
    // Derived seed: mix the root seed with the index so every slot in the battery
    // gets a distinct, reproducible seed. Kept as a 32-bit integer to survive any
    // downstream `>>> 0` normalization.
    const derived = (Math.imul(seed | 0, 0x9e3779b1) + Math.imul(i | 0, 0x85ebca6b)) | 0;
    pairs.push(gen.generate(derived));
  }
  return pairs;
}
